import { rest } from "msw";

//base movie URL to C&P for new handlers: https://api.themoviedb.org/3/

export const handlers = [
	rest.get("https://api.themoviedb.org/3/movie/550", (req, res, ctx) => {
		return res(
			ctx.status(200),
			ctx.json({
				adult: false,
				backdrop_path: "/fCayJrkfRaCRCTh8GqN30f8oyQF.jpg",
				belongs_to_collection: null,
				budget: 63000000,
				genres: [
					{
						id: 18,
						name: "Drama",
					},
				],
				homepage: "",
				id: 550,
				imdb_id: "tt0137523",
				original_language: "en",
				original_title: "Fight Club",
				overview:
					'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
				popularity: 0.5,
				poster_path: null,
				production_companies: [
					{
						id: 508,
						logo_path: "/7PzJdsLGlR7oW4J0J5Xcd0pHGRg.png",
						name: "Regency Enterprises",
						origin_country: "US",
					},
					{
						id: 711,
						logo_path: null,
						name: "Fox 2000 Pictures",
						origin_country: "",
					},
					{
						id: 20555,
						logo_path: null,
						name: "Taurus Film",
						origin_country: "",
					},
					{
						id: 54050,
						logo_path: null,
						name: "Linson Films",
						origin_country: "",
					},
					{
						id: 54051,
						logo_path: null,
						name: "Atman Entertainment",
						origin_country: "",
					},
					{
						id: 54052,
						logo_path: null,
						name: "Knickerbocker Films",
						origin_country: "",
					},
					{
						id: 25,
						logo_path: "/qZCc1lty5FzX30aOCVRBLzaVmcp.png",
						name: "20th Century Fox",
						origin_country: "US",
					},
				],
				production_countries: [
					{
						iso_3166_1: "US",
						name: "United States of America",
					},
				],
				release_date: "1999-10-12",
				revenue: 100853753,
				runtime: 139,
				spoken_languages: [
					{
						iso_639_1: "en",
						name: "English",
					},
				],
				status: "Released",
				tagline:
					"How much can you know about yourself if you've never been in a fight?",
				title: "Fight Club",
				video: false,
				vote_average: 7.8,
				vote_count: 3439,
			})
		);
	}),
	rest.get("https://api.themoviedb.org/3/movie/603692", (req, res, ctx) => {
		return res(
			ctx.status(200),
			ctx.json({
				adult: false,
				backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
				belongs_to_collection: {
					id: 404609,
					name: "John Wick Collection",
					poster_path: "/xUidyvYFsbbuExifLkslpcd8SMc.jpg",
					backdrop_path: "/fSwYa5q2xRkBoOOjueLpkLf3N1m.jpg",
				},
				budget: 90000000,
				genres: [
					{
						id: 28,
						name: "Action",
					},
					{
						id: 53,
						name: "Thriller",
					},
					{
						id: 80,
						name: "Crime",
					},
				],
				homepage: "https://johnwick.movie",
				id: 603692,
				imdb_id: "tt10366206",
				original_language: "en",
				original_title: "John Wick: Chapter 4",
				overview:
					"With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
				popularity: 950.477,
				poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
				production_companies: [
					{
						id: 3528,
						logo_path: "/cCzCClIzIh81Fa79hpW5nXoUsHK.png",
						name: "Thunder Road",
						origin_country: "US",
					},
					{
						id: 23008,
						logo_path: "/5SarYupipdiejsEqUkwu1SpYfru.png",
						name: "87Eleven",
						origin_country: "US",
					},
					{
						id: 1632,
						logo_path: "/cisLn1YAUuptXVBa0xjq7ST9cH0.png",
						name: "Lionsgate",
						origin_country: "US",
					},
					{
						id: 491,
						logo_path: "/rUp0lLKa1pr4UsPm8fgzmnNGxtq.png",
						name: "Summit Entertainment",
						origin_country: "US",
					},
					{
						id: 195559,
						logo_path: "/fmh0UMCOa7JsDr6UhLESPePc3PE.png",
						name: "El-Torky Art Production",
						origin_country: "",
					},
				],
				production_countries: [
					{
						iso_3166_1: "US",
						name: "United States of America",
					},
				],
				release_date: "2023-03-22",
				revenue: 0,
				runtime: 169,
				spoken_languages: [
					{
						english_name: "English",
						iso_639_1: "en",
						name: "English",
					},
					{
						english_name: "French",
						iso_639_1: "fr",
						name: "Français",
					},
					{
						english_name: "Japanese",
						iso_639_1: "ja",
						name: "日本語",
					},
				],
				status: "Released",
				tagline: "No way back, one way out.",
				title: "John Wick: Chapter 4",
				video: false,
				vote_average: 8.7,
				vote_count: 34,
			})
		);
	}),
	rest.get("https://api.themoviedb.org/3/person/287", (req, res, ctx) => {
		ctx.status(200);
		ctx.json({
			birthday: "1963-12-18",
			known_for_department: "Acting",
			deathday: null,
			id: 287,
			name: "Brad Pitt",
			also_known_as: [
				"برد پیت",
				"Бред Питт",
				"Бред Пітт",
				"Buratto Pitto",
				"Брэд Питт",
				"畢·彼特",
				"ブラッド・ピット",
				"브래드 피트",
				"براد بيت",
				"แบรด พิตต์",
			],
			gender: 2,
			biography:
				"William Bradley \"Brad\" Pitt (born December 18, 1963) is an American actor and film producer. Pitt has received two Academy Award nominations and four Golden Globe Award nominations, winning one. He has been described as one of the world's most attractive men, a label for which he has received substantial media attention. Pitt began his acting career with television guest appearances, including a role on the CBS prime-time soap opera Dallas in 1987. He later gained recognition as the cowboy hitchhiker who seduces Geena Davis's character in the 1991 road movie Thelma & Louise. Pitt's first leading roles in big-budget productions came with A River Runs Through It (1992) and Interview with the Vampire (1994). He was cast opposite Anthony Hopkins in the 1994 drama Legends of the Fall, which earned him his first Golden Globe nomination. In 1995 he gave critically acclaimed performances in the crime thriller Seven and the science fiction film 12 Monkeys, the latter securing him a Golden Globe Award for Best Supporting Actor and an Academy Award nomination.\n\nFour years later, in 1999, Pitt starred in the cult hit Fight Club. He then starred in the major international hit as Rusty Ryan in Ocean's Eleven (2001) and its sequels, Ocean's Twelve (2004) and Ocean's Thirteen (2007). His greatest commercial successes have been Troy (2004) and Mr. & Mrs. Smith (2005).\n\nPitt received his second Academy Award nomination for his title role performance in the 2008 film The Curious Case of Benjamin Button. Following a high-profile relationship with actress Gwyneth Paltrow, Pitt was married to actress Jennifer Aniston for five years. Pitt lives with actress Angelina Jolie in a relationship that has generated wide publicity. He and Jolie have six children—Maddox, Pax, Zahara, Shiloh, Knox, and Vivienne.\n\nSince beginning his relationship with Jolie, he has become increasingly involved in social issues both in the United States and internationally. Pitt owns a production company named Plan B Entertainment, whose productions include the 2007 Academy Award winning Best Picture, The Departed.",
			popularity: 10.647,
			place_of_birth: "Shawnee, Oklahoma, USA",
			profile_path: "/kU3B75TyRiCgE270EyZnHjfivoq.jpg",
			adult: false,
			imdb_id: "nm0000093",
			homepage: null,
		});
	}),
	rest.get("https://api.themoviedb.org/3/search/person", (req, res, ctx) => {
		const { query } = req.params;
		if (query === "Bradley") {
			ctx.status(200);
			ctx.json({
				page: 1,
				results: [
					{
						adult: false,
						gender: 2,
						id: 51329,
						known_for_department: "Acting",
						name: "Bradley Cooper",
						original_name: "Bradley Cooper",
						popularity: 29.09,
						profile_path: "/DPnessSsWqVXRbKm93PtMjB4Us.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/2o0PKGmnSgCGkzoSePNAqse8Ure.jpg",
								id: 18785,
								title: "The Hangover",
								original_language: "en",
								original_title: "The Hangover",
								overview:
									"When three friends finally come to after a raucous night of bachelor-party revelry, they find a baby in the closet and a tiger in the bathroom. But they can't seem to locate their best friend, Doug – who's supposed to be tying the knot. Launching a frantic search for Doug, the trio perseveres through a nasty hangover to try to make it to the church on time.",
								poster_path: "/uluhlXubGu1VxU63X9VHCLWDAYP.jpg",
								media_type: "movie",
								genre_ids: [35],
								popularity: 116.515,
								release_date: "2009-06-02",
								video: false,
								vote_average: 7.309,
								vote_count: 15269,
							},
							{
								adult: false,
								backdrop_path: "/nrpivVyJjRQqVDhRTZWVPWqYwQp.jpg",
								id: 190859,
								title: "American Sniper",
								original_language: "en",
								original_title: "American Sniper",
								overview:
									"U.S. Navy SEAL Chris Kyle takes his sole mission—protect his comrades—to heart and becomes one of the most lethal snipers in American history. His pinpoint accuracy not only saves countless lives but also makes him a prime target of insurgents. Despite grave danger and his struggle to be a good husband and father to his family back in the States, Kyle serves four tours of duty in Iraq. However, when he finally returns home, he finds that he cannot leave the war behind.",
								poster_path: "/i1U46OwMc6vlm7OoSUKfqUH615e.jpg",
								media_type: "movie",
								genre_ids: [10752, 28],
								popularity: 94.213,
								release_date: "2014-12-25",
								video: false,
								vote_average: 7.433,
								vote_count: 11727,
							},
							{
								adult: false,
								backdrop_path: "/t5cuFKDgf5hRWYpRZ3jAANu5kPr.jpg",
								id: 82693,
								title: "Silver Linings Playbook",
								original_language: "en",
								original_title: "Silver Linings Playbook",
								overview:
									"After spending eight months in a mental institution, a former teacher moves back in with his parents and tries to reconcile with his ex-wife.",
								poster_path: "/y7iOVneBvITlBdhy6tVqXVOa1Js.jpg",
								media_type: "movie",
								genre_ids: [18, 35, 10749],
								popularity: 29.709,
								release_date: "2012-11-16",
								video: false,
								vote_average: 7.1,
								vote_count: 11007,
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 94330,
						known_for_department: "Acting",
						name: "David Bradley",
						original_name: "David Bradley",
						popularity: 13.412,
						profile_path: "/uu275GxZrHfqcaBJx6DeSuHEYWy.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/pXqA3aUxrsdUbthRqBhnNUi0RVe.jpg",
								id: 25682,
								title: "American Ninja 3: Blood Hunt",
								original_language: "en",
								original_title: "American Ninja 3: Blood Hunt",
								overview:
									'Jackson is back, and now he has a new partner, karate champion Sean, as they must face a deadly terrorist known as "The Cobra", who has infected Sean with a virus. Sean and Jackson have no choice but to fight the Cobra and his bands of ninjas.',
								poster_path: "/oiKM4CAEXrhAfDkpnhBW8RpOQC7.jpg",
								media_type: "movie",
								genre_ids: [28, 12, 18],
								popularity: 9.636,
								release_date: "1989-02-24",
								video: false,
								vote_average: 4.669,
								vote_count: 136,
							},
							{
								adult: false,
								backdrop_path: "/6Y9Gd1GBge8LMV60xhk6XCUmNMI.jpg",
								id: 25684,
								title: "American Ninja 5",
								original_language: "en",
								original_title: "American Ninja 5",
								overview:
									"When a scientists daughter is kidnapped, American Ninja, attempts to find her, but this time he teams up with a youngster he has trained in the ways of the ninja.",
								poster_path: "/feLMfivbHHla844jWrVnqgzU0Zh.jpg",
								media_type: "movie",
								genre_ids: [28, 53],
								popularity: 10.254,
								release_date: "1993-01-01",
								video: false,
								vote_average: 4.719,
								vote_count: 96,
							},
							{
								adult: false,
								backdrop_path: "/lDtTiBO8CyLhbsi7idZe2MQDXTB.jpg",
								id: 25528,
								title: "American Ninja 4: The Annihilation",
								original_language: "en",
								original_title: "American Ninja 4: The Annihilation",
								overview:
									"The two American Ninjas, Joe Armstrong and Sean Davidson, team up to do battle against a terrorist and his band of Ninjas.",
								poster_path: "/3MoXMlTDQgpLr54veMT39rCyaTz.jpg",
								media_type: "movie",
								genre_ids: [28, 53],
								popularity: 11.404,
								release_date: "1990-10-30",
								video: false,
								vote_average: 5.226,
								vote_count: 124,
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 11180,
						known_for_department: "Acting",
						name: "David Bradley",
						original_name: "David Bradley",
						popularity: 14.376,
						profile_path: "/rDp3nmZTZIYokp3aSOzClpDkVlS.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
								id: 671,
								title: "Harry Potter and the Philosopher's Stone",
								original_language: "en",
								original_title: "Harry Potter and the Philosopher's Stone",
								overview:
									"Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.",
								poster_path: "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
								media_type: "movie",
								genre_ids: [12, 14],
								popularity: 244.962,
								release_date: "2001-11-16",
								video: false,
								vote_average: 7.913,
								vote_count: 24426,
							},
							{
								adult: false,
								backdrop_path: "/urDWNffjwmNi5IQaezw9GwqkUXa.jpg",
								id: 767,
								title: "Harry Potter and the Half-Blood Prince",
								original_language: "en",
								original_title: "Harry Potter and the Half-Blood Prince",
								overview:
									"As Lord Voldemort tightens his grip on both the Muggle and wizarding worlds, Hogwarts is no longer a safe haven. Harry suspects perils may even lie within the castle, but Dumbledore is more intent upon preparing him for the final battle fast approaching. Together they work to find the key to unlock Voldemorts defenses and to this end, Dumbledore recruits his old friend and colleague Horace Slughorn, whom he believes holds crucial information. Even as the decisive showdown looms, romance blossoms for Harry, Ron, Hermione and their classmates. Love is in the air, but danger lies ahead and Hogwarts may never be the same again.",
								poster_path: "/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg",
								media_type: "movie",
								genre_ids: [12, 14],
								popularity: 209.35,
								release_date: "2009-07-07",
								video: false,
								vote_average: 7.699,
								vote_count: 17442,
							},
							{
								adult: false,
								backdrop_path: "/7tbeoSTWW2cWPecjQo9fcdf0Hzv.jpg",
								id: 672,
								title: "Harry Potter and the Chamber of Secrets",
								original_language: "en",
								original_title: "Harry Potter and the Chamber of Secrets",
								overview:
									"Cars fly, trees fight back, and a mysterious house-elf comes to warn Harry Potter at the start of his second year at Hogwarts. Adventure and danger await when bloody writing on a wall announces: The Chamber Of Secrets Has Been Opened. To save Hogwarts will require all of Harry, Ron and Hermione’s magical abilities and courage.",
								poster_path: "/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg",
								media_type: "movie",
								genre_ids: [12, 14],
								popularity: 227.355,
								release_date: "2002-11-13",
								video: false,
								vote_average: 7.723,
								vote_count: 19624,
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 154689,
						known_for_department: "Acting",
						name: "Bradley James",
						original_name: "Bradley James",
						popularity: 12.882,
						profile_path: "/djYjl9kE2VPSO3qLnC8Jo3aD8d2.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/dxyUN2kMhr0gMBKQpE79Z4sWAp5.jpg",
								id: 346672,
								title: "Underworld: Blood Wars",
								original_language: "en",
								original_title: "Underworld: Blood Wars",
								overview:
									"Vampire death dealer Selene fends off brutal attacks from both the Lycan clan and the Vampire faction that betrayed her. With her only allies, David and his father Thomas, she must stop the eternal war between Lycans and Vampires, even if it means she has to make the ultimate sacrifice.",
								poster_path: "/v1ciDCWMG47gdT4kMyjyQbnLQQn.jpg",
								media_type: "movie",
								genre_ids: [14, 28, 53, 27],
								popularity: 59.927,
								release_date: "2016-11-24",
								video: false,
								vote_average: 5.824,
								vote_count: 3309,
							},
							{
								adult: false,
								backdrop_path: "/tCjXy1iCsr2BVlNczafnkZ40LPn.jpg",
								id: 60866,
								name: "iZombie",
								original_language: "en",
								original_name: "iZombie",
								overview:
									"A medical student who becomes a zombie joins a Coroner's Office in order to gain access to the brains she must reluctantly eat so that she can maintain her humanity. But every brain she eats, she also inherits their memories and must now solve their deaths with help from the Medical examiner and a police detective.",
								poster_path: "/q4nqNwAhzVR7JuYctrWJvUWz3xR.jpg",
								media_type: "tv",
								genre_ids: [18, 80, 10765],
								popularity: 83.139,
								first_air_date: "2015-03-17",
								vote_average: 7.8,
								vote_count: 2579,
								origin_country: ["US"],
							},
							{
								adult: false,
								backdrop_path: "/qHkXVksHVPycW7CGQ4B8RlgMgAE.jpg",
								id: 7225,
								name: "Merlin",
								original_language: "en",
								original_name: "Merlin",
								overview:
									"The unlikely friendship between Merlin, a young man gifted with extraordinary magical powers, and Prince Arthur, heir to the crown of Camelot.",
								poster_path: "/8eR5Jg7CxsuCOEBU5wW0opObxpi.jpg",
								media_type: "tv",
								genre_ids: [10759, 18, 10765],
								popularity: 75.237,
								first_air_date: "2008-09-20",
								vote_average: 7.812,
								vote_count: 765,
								origin_country: ["GB"],
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 226370,
						known_for_department: "Acting",
						name: "Bradley Steven Perry",
						original_name: "Bradley Steven Perry",
						popularity: 6.784,
						profile_path: "/n62ZTaV7xFfOICwcSa6l2hC1K8v.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/zIxWFekMJkxUFp52xAWSP0mhB8k.jpg",
								id: 60405,
								title: "Sharpay's Fabulous Adventure",
								original_language: "en",
								original_title: "Sharpay's Fabulous Adventure",
								overview:
									"After a talent scout spots her performing with her dog Boi at a charity gala, Sharpay Evans sets off for the bright lights of NYC, convinced instant fame and fortune are in the bag. But theatre's a dog-eat-dog world. Fortunately, Sharpay also meets Peyton, a handsome student filmmaker who finds Sharpay nearly as fascinating as she finds herself.",
								poster_path: "/aPtBzBKCCvByXue1AZrG2lrxm4l.jpg",
								media_type: "movie",
								genre_ids: [10751, 10402],
								popularity: 19.842,
								release_date: "2011-04-19",
								video: false,
								vote_average: 6.0,
								vote_count: 503,
							},
							{
								adult: false,
								backdrop_path: "/vWwSPYymDv7gZ1C1yzgNuEacbKy.jpg",
								id: 21641,
								name: "Good Luck Charlie",
								original_language: "en",
								original_name: "Good Luck Charlie",
								overview:
									"Teens PJ and Teddy and tween brother Gabe are typical kids -- that is, until their mother has another baby. The arrival of their new sister completely upends the entire household. When their mother heads back to work after Charlie's birth, it's up to the kids and their dad to keep the home fires burning -- and to keep Charlie out of trouble as she learns to sit up, crawl, walk and run. Teddy, as the older sister, makes a personalized video diary for Charlie, in each episode adding a nugget of wisdom for her baby sibling.",
								poster_path: "/cyYwkXW1vd3YpiFVlb7y0hgIzuu.jpg",
								media_type: "tv",
								genre_ids: [35, 10751, 10762],
								popularity: 45.387,
								first_air_date: "2010-04-04",
								vote_average: 7.947,
								vote_count: 314,
								origin_country: ["US", "GB"],
							},
							{
								adult: false,
								backdrop_path: "/3SXATaC4JZA8qxLyAUFjcq17BBV.jpg",
								id: 81440,
								title: "Good Luck Charlie, It's Christmas!",
								original_language: "en",
								original_title: "Good Luck Charlie, It's Christmas!",
								overview:
									"Teddy Duncan's middle-class family embarks on a road trip from their home in Denver to visit Mrs. Duncans Parents, the Blankenhoopers, in Palm Springs. When they find themselves stranded between Denver and Utah, they try to hitch a ride to Las Vegas with a seemingly normal older couple in a station wagon from Roswell, New Mexico. It turns out that the couple believes they are the victims of alien abduction. The Duncan's must resort to purchasing a clunker Yugo to get to Utah, have their luggage stolen in Las Vegas, and survive a zany Christmas with Grandpa and Grandma Blankenhooper.",
								poster_path: "/3EFdgTFkN33CF0b8T04V1lwAooI.jpg",
								media_type: "movie",
								genre_ids: [10770, 35, 10751],
								popularity: 13.188,
								release_date: "2011-12-08",
								video: false,
								vote_average: 6.665,
								vote_count: 376,
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 11367,
						known_for_department: "Acting",
						name: "Bradley Whitford",
						original_name: "Bradley Whitford",
						popularity: 13.677,
						profile_path: "/oeDv2qZWTxELLaNtOIoeG72leNY.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/jDXOmBG97WOlT5iog0kxMBShDTN.jpg",
								id: 419430,
								title: "Get Out",
								original_language: "en",
								original_title: "Get Out",
								overview:
									"Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family's overly accommodating behavior as nervous attempts to deal with their daughter's interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he never could have imagined.",
								poster_path: "/mE24wUCfjK8AoBBjaMjho7Rczr7.jpg",
								media_type: "movie",
								genre_ids: [9648, 53, 27],
								popularity: 56.102,
								release_date: "2017-02-24",
								video: false,
								vote_average: 7.615,
								vote_count: 15400,
							},
							{
								adult: false,
								backdrop_path: "/5iiVfPS6LsAqmVQVOzhyCHhCFgU.jpg",
								id: 22970,
								title: "The Cabin in the Woods",
								original_language: "en",
								original_title: "The Cabin in the Woods",
								overview:
									"Five friends go for a break at a remote cabin, where they get more than they bargained for, discovering the truth behind the cabin in the woods.",
								poster_path: "/kjDXrK3ReIwuDrpWElI5OQkKYTA.jpg",
								media_type: "movie",
								genre_ids: [27, 14],
								popularity: 49.368,
								release_date: "2012-04-12",
								video: false,
								vote_average: 6.6,
								vote_count: 6997,
							},
							{
								adult: false,
								backdrop_path: "/uovH5k4BAEPqXqxgwVrTtqH169g.jpg",
								id: 373571,
								title: "Godzilla: King of the Monsters",
								original_language: "en",
								original_title: "Godzilla: King of the Monsters",
								overview:
									"Follows the heroic efforts of the crypto-zoological agency Monarch as its members face off against a battery of god-sized monsters, including the mighty Godzilla, who collides with Mothra, Rodan, and his ultimate nemesis, the three-headed King Ghidorah. When these ancient super-species, thought to be mere myths, rise again, they all vie for supremacy, leaving humanity's very existence hanging in the balance.",
								poster_path: "/fQ40gmFM4p03tXwMxQQKh2cCBW4.jpg",
								media_type: "movie",
								genre_ids: [878, 28],
								popularity: 78.095,
								release_date: "2019-05-29",
								video: false,
								vote_average: 6.673,
								vote_count: 5243,
							},
						],
					},
					{
						adult: false,
						gender: 1,
						id: 58430,
						known_for_department: "Acting",
						name: "Ruth Bradley",
						original_name: "Ruth Bradley",
						popularity: 12.148,
						profile_path: "/pnrFYG3Ij8Op6XTpbFw2vdltDwR.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/ui4PGuwc9SakCxj0qWbQZ129Uis.jpg",
								id: 84204,
								title: "Grabbers",
								original_language: "en",
								original_title: "Grabbers",
								overview:
									"Something sinister has come to the shores of Erin Island, unbeknownst to the quaint population of this sleepy fishing village resting somewhere off Ireland’s coast. First, some fishermen go missing. Then there is the rash of whale carcasses suddenly washing up on the beach. When the murders start, it’s up to two mismatched cops – an irresponsible alcoholic and his new partner, a by-the-book woman from the mainland – to protect the townsfolk from the giant, bloodsucking, tentacled aliens that prey upon them. Their only weapon, they discover, is booze. If they want to survive the creatures’ onslaught, everyone will have to get very, very drunk!",
								poster_path: "/dGAIjxYqP9YBLHeAmaE1NstSnqW.jpg",
								media_type: "movie",
								genre_ids: [878, 35, 53, 27, 9648],
								popularity: 11.105,
								release_date: "2012-08-10",
								video: false,
								vote_average: 6.1,
								vote_count: 378,
							},
							{
								adult: false,
								backdrop_path: "/jHHaLH1ZFNaIjIQqZDN1f6hq12K.jpg",
								id: 570352,
								title: "Agatha and the Truth of Murder",
								original_language: "en",
								original_title: "Agatha and the Truth of Murder",
								overview:
									"England, December 1926. Although her personal life is in tatters, the famous writer Agatha Christie decides to leave everything behind to help unravel an unsolved murder committed on a train six years ago, unable to imagine the disproportionate consequences that such a selfless act will cause.",
								poster_path: "/c9RzNEpejLkEBVH7cGNekpec8hS.jpg",
								media_type: "movie",
								genre_ids: [18, 9648],
								popularity: 14.071,
								release_date: "2018-12-23",
								video: false,
								vote_average: 6.23,
								vote_count: 111,
							},
							{
								adult: false,
								backdrop_path: "/98sIdYdvnh68Va1JLjcyAuFGZO5.jpg",
								id: 466081,
								title: "The Informer",
								original_language: "en",
								original_title: "The Informer",
								overview:
									"In New York, former convict Pete Koslow, related to the Polish mafia, must deal with both Klimek the General, his ruthless boss, and the twisted ambitions of two federal agents, as he tries to survive and protect the lives of his loved ones.",
								poster_path: "/pbGveUC8mk0QRkdXpERPLbMFnrg.jpg",
								media_type: "movie",
								genre_ids: [18, 80, 53],
								popularity: 16.379,
								release_date: "2019-08-30",
								video: false,
								vote_average: 6.516,
								vote_count: 668,
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 98661,
						known_for_department: "Acting",
						name: "Bradley Stryker",
						original_name: "Bradley Stryker",
						popularity: 7.696,
						profile_path: "/3h0F6HRz4He5ESx9mIIIGV90MF2.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/8bQbejOvAKe78RXxpkfM04n0K18.jpg",
								id: 310,
								title: "Bruce Almighty",
								original_language: "en",
								original_title: "Bruce Almighty",
								overview:
									"Bruce Nolan toils as a 'human interest' television reporter in Buffalo, N.Y., but despite his high ratings and the love of his beautiful girlfriend, Bruce remains unfulfilled. At the end of the worst day in his life, he angrily ridicules God—and the Almighty responds, endowing Bruce with all of His divine powers.",
								poster_path: "/f0QqG14SZYYZcV4VWykVc5w13dz.jpg",
								media_type: "movie",
								genre_ids: [14, 35],
								popularity: 80.078,
								release_date: "2003-05-23",
								video: false,
								vote_average: 6.699,
								vote_count: 9674,
							},
							{
								adult: false,
								backdrop_path: "/aiM3XxYE2JvW1vJ4AC6cI1RjAoT.jpg",
								id: 438650,
								title: "Cold Pursuit",
								original_language: "en",
								original_title: "Cold Pursuit",
								overview:
									"The quiet family life of Nels Coxman, a snowplow driver, is upended after his son's murder. Nels begins a vengeful hunt for Viking, the drug lord he holds responsible for the killing, eliminating Viking's associates one by one. As Nels draws closer to Viking, his actions bring even more unexpected and violent consequences, as he proves that revenge is all in the execution.",
								poster_path: "/hXgmWPd1SuujRZ4QnKLzrj79PAw.jpg",
								media_type: "movie",
								genre_ids: [28, 80, 53],
								popularity: 38.12,
								release_date: "2019-02-07",
								video: false,
								vote_average: 5.742,
								vote_count: 2219,
							},
							{
								adult: false,
								backdrop_path: "/60UN7vvcWWggLe0Uz9EFZJx718P.jpg",
								id: 879538,
								title: "Crawlspace",
								original_language: "en",
								original_title: "Crawlspace",
								overview:
									"After witnessing a brutal murder in a cabin, a man hides in a crawlspace while the killers scour the property for a hidden fortune. As they draw nearer, he must decide if the crawlspace will be his tomb or the battleground in his fight for survival.",
								poster_path: "/yZVByCjWvKdSWcYLacoFmnOoSpm.jpg",
								media_type: "movie",
								genre_ids: [53],
								popularity: 155.35,
								release_date: "2022-03-31",
								video: false,
								vote_average: 6.6,
								vote_count: 82,
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 23680,
						known_for_department: "Acting",
						name: "Dee Bradley Baker",
						original_name: "Dee Bradley Baker",
						popularity: 9.8,
						profile_path: "/9oFnToDZWp0I484s7Ua1EzNQQ2m.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/sjxtIUCWR74yPPcZFfTsToepfWm.jpg",
								id: 105971,
								name: "Star Wars: The Bad Batch",
								original_language: "en",
								original_name: "Star Wars: The Bad Batch",
								overview:
									"The 'Bad Batch' of elite and experimental clones make their way through an ever-changing galaxy in the immediate aftermath of the Clone Wars.",
								poster_path: "/5Q6z9bjy8dHKA5T8kNmCd8hj6Gl.jpg",
								media_type: "tv",
								genre_ids: [16, 10759, 10765],
								popularity: 155.077,
								first_air_date: "2021-05-04",
								vote_average: 8.342,
								vote_count: 717,
								origin_country: ["US"],
							},
							{
								adult: false,
								backdrop_path: "/xEdnGUc8KeZ7h0eEgSN3ERhjgL0.jpg",
								id: 12180,
								title: "Star Wars: The Clone Wars",
								original_language: "en",
								original_title: "Star Wars: The Clone Wars",
								overview:
									"Set between Episode II and III, The Clone Wars is the first computer animated Star Wars film. Anakin and Obi Wan must find out who kidnapped Jabba the Hutt's son and return him safely. The Separatists will try anything to stop them and ruin any chance of a diplomatic agreement between the Hutts and the Republic.",
								poster_path: "/d6YOfi0T9GowglzIkDQGGvGYVTM.jpg",
								media_type: "movie",
								genre_ids: [16, 28, 878, 12],
								popularity: 22.633,
								release_date: "2008-08-05",
								video: false,
								vote_average: 6.116,
								vote_count: 1721,
							},
							{
								adult: false,
								backdrop_path: "/nLKYAJCEi6OQVji1HJIxSQ74H9s.jpg",
								id: 246,
								name: "Avatar: The Last Airbender",
								original_language: "en",
								original_name: "Avatar: The Last Airbender",
								overview:
									"In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.",
								poster_path: "/cHFZA8Tlv03nKTGXhLOYOLtqoSm.jpg",
								media_type: "tv",
								genre_ids: [16, 10759, 10765],
								popularity: 59.033,
								first_air_date: "2005-02-21",
								vote_average: 8.687,
								vote_count: 3187,
								origin_country: ["US"],
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 134686,
						known_for_department: "Acting",
						name: "Bradley James Allan",
						original_name: "Bradley James Allan",
						popularity: 5.268,
						profile_path: "/mHqzf5W1Jxmlp27V9z3WA6ALiFP.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/zzFTSEAZcLGSbGipQVflSNUqpij.jpg",
								id: 5175,
								title: "Rush Hour 2",
								original_language: "en",
								original_title: "Rush Hour 2",
								overview:
									"It's vacation time for Carter as he finds himself alongside Lee in Hong Kong wishing for more excitement. While Carter wants to party and meet the ladies, Lee is out to track down a Triad gang lord who may be responsible for killing two men at the American Embassy. Things get complicated as the pair stumble onto a counterfeiting plot. The boys are soon up to their necks in fist fights and life-threatening situations. A trip back to the U.S. may provide the answers about the bombing, the counterfeiting, and the true allegiance of sexy customs agent Isabella.",
								poster_path: "/aBQf2vMiCINeVC9v6BGVYKXurTh.jpg",
								media_type: "movie",
								genre_ids: [28, 35, 80],
								popularity: 53.205,
								release_date: "2001-08-03",
								video: false,
								vote_average: 6.697,
								vote_count: 3478,
							},
							{
								adult: false,
								backdrop_path: "/pLIX7upqGs5RKG2Z5Xbt9i4ziOH.jpg",
								id: 10951,
								title: "Gorgeous",
								original_language: "cn",
								original_title: "玻璃樽",
								overview:
									"When Ah Bu, a girl from a small fishing town in Taiwan, finds a glass bottle with a romantic message, she travels to Hong Kong to find her prince charming. As it turns out, her prince charming, Albert, happens to be gay. But all is not lost when Ah Bu meets the dashing Chi Wu. Meanwhile, Ah Bu's boyfriend from Taiwan comes looking for her, as the action and romance follow Ah Bu back to Taiwan.",
								poster_path: "/vzY0zAdfnLZaVQrQcivasBDTmm4.jpg",
								media_type: "movie",
								genre_ids: [12, 28, 35, 10749],
								popularity: 28.282,
								release_date: "1999-02-12",
								video: false,
								vote_average: 6.285,
								vote_count: 307,
							},
							{
								adult: false,
								backdrop_path: "/wFuUDqlO3pvkhBooVz9ZFnWCpbr.jpg",
								id: 8697,
								title: "Who Am I?",
								original_language: "cn",
								original_title: "我是誰",
								overview:
									'A group of covert CIA operatives trailing a potential new energy source are double-crossed by corrupt agent Morgan, who causes a helicopter crash in remote South Africa. The sole survivor, suffering severe amnesia, is nursed to recovery by a kindly native tribe who call him "Whoami" after the question he keeps asking. With the help of a mysterious reporter Christine, Whoami pieces together his past and tracks the turncoat agent and his criminal cohorts.',
								poster_path: "/9YDKLbBmWGpxG5bO3TBawtNNOAr.jpg",
								media_type: "movie",
								genre_ids: [12, 28, 35, 53],
								popularity: 23.781,
								release_date: "1998-01-17",
								video: false,
								vote_average: 7.108,
								vote_count: 729,
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 1413289,
						known_for_department: "Acting",
						name: "Bradley Freegard",
						original_name: "Bradley Freegard",
						popularity: 3.867,
						profile_path: "/5wlFeOvasxF5DriBTq8CrFuvg6K.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/k47JEUTQsSMN532HRg6RCzZKBdB.jpg",
								id: 116135,
								name: "Vikings: Valhalla",
								original_language: "en",
								original_name: "Vikings: Valhalla",
								overview:
									'In this sequel to "Vikings," a hundred years have passed and a new generation of legendary heroes arises to forge its own destiny — and make history.',
								poster_path: "/rDFy1fUU6OC3Mm0CLFB7u0fGwVN.jpg",
								media_type: "tv",
								genre_ids: [10759, 18, 10768],
								popularity: 154.433,
								first_air_date: "2022-02-25",
								vote_average: 7.905,
								vote_count: 584,
								origin_country: ["US"],
							},
							{
								adult: false,
								backdrop_path: "/4PrbHZ3XNWedhKNSSi4Nwb9L5By.jpg",
								id: 75592,
								name: "Keeping Faith",
								original_language: "cy",
								original_name: "Un Bore Mercher",
								overview:
									"Faith, a small-town Welsh lawyer, is forced to cut short her extended maternity leave when her husband and business partner, Evan, goes missing.  As the truth of his actions surface, Faith must fight to protect her family and her sanity.",
								poster_path: "/loZ2f0rbBwwnGXr6lSaOA4dGPV3.jpg",
								media_type: "tv",
								genre_ids: [9648, 18],
								popularity: 8.0,
								first_air_date: "2017-11-05",
								vote_average: 7.192,
								vote_count: 26,
								origin_country: ["GB"],
							},
							{
								adult: false,
								backdrop_path: "/slT8sqHNSNLttTltq3yUTq67qII.jpg",
								id: 314406,
								title: "Under Milk Wood",
								original_language: "en",
								original_title: "Dan y Wenallt",
								overview:
									'Two versions of Dylan Thomas\' classic play "Under Milk Wood" were shot, with the same cast, one in Welsh,  "Dan y Wenallt", and one in English. Directed by Kevin Allen, narrated by and starring Rhys Ifans, the films were shot largely in the Pembrokeshire village of Solfa during the summer of 2014.  This surreal and erotic interpretation of Dylan Thomas\' work is the first theatrical production of the brilliant, haunting radio play since Elizabeth Taylor and Richard Burton\'s 1972 film. Certain to astonish and excite in equal measures, this production reunites director Kevin Allen with actor Rhys Ifans over 15 years after the release of their cult classic "Twin Town". An ensemble Welsh speaking cast of familiar faces is led by Ifans as First Voice and Captain Cat, with Charlotte Church as Polly Garter.',
								poster_path: "/5MKg1B6BqWYFtn4JHOFhWGQwmAJ.jpg",
								media_type: "movie",
								genre_ids: [18],
								popularity: 1.975,
								release_date: "2015-06-20",
								video: false,
								vote_average: 5.9,
								vote_count: 7,
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 1357431,
						known_for_department: "Acting",
						name: "David Bradley",
						original_name: "David Bradley",
						popularity: 3.105,
						profile_path: "/s8zd1IBotKq1lQUQfX5tI1b8a5v.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/eWvxOS5g67B1b46Cff9TlYuJleY.jpg",
								id: 13384,
								title: "Kes",
								original_language: "en",
								original_title: "Kes",
								overview:
									"A young, English working-class boy spends his free time caring for and training his pet falcon.",
								poster_path: "/r1FMq75irhsQBVGjXhPU4xA9SDo.jpg",
								media_type: "movie",
								genre_ids: [18],
								popularity: 9.931,
								release_date: "1970-04-03",
								video: false,
								vote_average: 7.521,
								vote_count: 333,
							},
							{
								adult: false,
								backdrop_path: "/iG1bvQKGKx8oPIGhwBzp9NDrRjW.jpg",
								id: 136418,
								title: "Hummingbird",
								original_language: "en",
								original_title: "Hummingbird",
								overview:
									"Homeless and on the run from a military court martial, a damaged ex-special forces soldier navigating London's criminal underworld seizes an opportunity to assume another man's identity, transforming into an avenging angel in the process.",
								poster_path: "/bN2aGUOxHRwGms68WTDr2MHzkKa.jpg",
								media_type: "movie",
								genre_ids: [28, 53],
								popularity: 31.804,
								release_date: "2013-05-07",
								video: false,
								vote_average: 6.176,
								vote_count: 1485,
							},
							{
								adult: false,
								backdrop_path: "/lPFq4Mv18bNGHYLjYEvYOBB3ilc.jpg",
								id: 10912,
								title: "All Quiet on the Western Front",
								original_language: "en",
								original_title: "All Quiet on the Western Front",
								overview:
									"At the start of World War I, Paul Baumer is a young German patriot, eager to fight. Indoctrinated with propaganda at school, he and his friends eagerly sign up for the army soon after graduation. But when the horrors of war soon become too much to bear, and as his friends die or become gravely wounded, Paul questions the sanity of fighting over a few hundreds yards of war-torn countryside.",
								poster_path: "/2HHFfieloWJcIz5PU3NKrv1i6DJ.jpg",
								media_type: "movie",
								genre_ids: [10752, 18, 10770],
								popularity: 32.29,
								release_date: "1979-11-14",
								video: false,
								vote_average: 6.61,
								vote_count: 154,
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 73040,
						known_for_department: "Acting",
						name: "Doug Bradley",
						original_name: "Doug Bradley",
						popularity: 3.004,
						profile_path: "/7RRelx5RlEbWhGRSUQMqo7KPTzg.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/1dFKtwFarEj47JRJHe9dPpMLyQF.jpg",
								id: 125509,
								title: "Wrong Turn 5: Bloodlines",
								original_language: "en",
								original_title: "Wrong Turn 5: Bloodlines",
								overview:
									"A small West Virginia town is hosting the legendary Mountain Man Festival on Halloween, where throngs of costumed party goers gather for a wild night of music and mischief. But an inbred family of hillbilly cannibals kill the fun when they trick and treat themselves to a group of visiting college students.",
								poster_path: "/nALE9wbgwIYKuwdhANoLbxasw7z.jpg",
								media_type: "movie",
								genre_ids: [27, 53],
								popularity: 72.313,
								release_date: "2012-10-23",
								video: false,
								vote_average: 5.388,
								vote_count: 790,
							},
							{
								adult: false,
								backdrop_path: "/kZY6JbihG9lqiOpYqU33XGfI4PW.jpg",
								id: 11569,
								title: "Hellraiser III: Hell on Earth",
								original_language: "en",
								original_title: "Hellraiser III: Hell on Earth",
								overview:
									"Pinhead is trapped in the Pillar of Souls. Fortunately for him it is bought by a young playboy who owns his own nightclub. Pinhead busies himself escaping by getting the playboy to lure victims to his presence so he can use their blood. Once free, he seeks to destroy the puzzle box so he need never return to Hell, but a female reporter is investigating the grisly murders and stands in his way.",
								poster_path: "/eBKrmVD29BQGDlWQJ3rKS8cmPGh.jpg",
								media_type: "movie",
								genre_ids: [27],
								popularity: 16.096,
								release_date: "1992-09-11",
								video: false,
								vote_average: 5.649,
								vote_count: 615,
							},
							{
								adult: false,
								backdrop_path: "/4SxXppJUwjQnd98VLxQEHvH3CfR.jpg",
								id: 9003,
								title: "Hellraiser",
								original_language: "en",
								original_title: "Hellraiser",
								overview:
									"After tinkering with a box he bought while abroad, sexual deviant Frank inadvertently opens a portal to hell, where fetish-demons led by Pinhead tear his body apart. When Frank’s brother and his wife move into his house, a skeletal Frank appears to his sister-in-law and asks her to supply him with corpses for his regeneration.",
								poster_path: "/nnYHvA2tSVdtr8KxIy8F6YndCOy.jpg",
								media_type: "movie",
								genre_ids: [27, 53],
								popularity: 31.049,
								release_date: "1987-09-11",
								video: false,
								vote_average: 6.9,
								vote_count: 2097,
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 1010135,
						known_for_department: "Acting",
						name: "John Bradley",
						original_name: "John Bradley",
						popularity: 3.938,
						profile_path: "/eLcisM9qqCLWnf0iImHuSn08FOi.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
								id: 1399,
								name: "Game of Thrones",
								original_language: "en",
								original_name: "Game of Thrones",
								overview:
									"Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
								poster_path: "/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg",
								media_type: "tv",
								genre_ids: [10765, 18, 10759],
								popularity: 545.397,
								first_air_date: "2011-04-17",
								vote_average: 8.436,
								vote_count: 20772,
								origin_country: ["US"],
							},
							{
								adult: false,
								backdrop_path: "/8QpzqK3nPGxpqpKqhe6QasTGBWQ.jpg",
								id: 406759,
								title: "Moonfall",
								original_language: "en",
								original_title: "Moonfall",
								overview:
									"A mysterious force knocks the moon from its orbit around Earth and sends it hurtling on a collision course with life as we know it.",
								poster_path: "/odVv1sqVs0KxBXiA8bhIBlPgalx.jpg",
								media_type: "movie",
								genre_ids: [878],
								popularity: 179.021,
								release_date: "2022-02-03",
								video: false,
								vote_average: 6.385,
								vote_count: 2303,
							},
							{
								adult: false,
								backdrop_path: "/mJQf866IDnWw7ZkFEM2Oz7QfhW0.jpg",
								id: 615904,
								title: "Marry Me",
								original_language: "en",
								original_title: "Marry Me",
								overview:
									"Music superstars Kat Valdez and Bastian are getting married before a global audience of fans. But when Kat learns, seconds before her vows, that Bastian has been unfaithful, she decides to marry Charlie, a stranger in the crowd, instead.",
								poster_path: "/ko1JVbGj4bT8IhCWqjBQ6ZtF2t.jpg",
								media_type: "movie",
								genre_ids: [10749, 35, 10402],
								popularity: 50.802,
								release_date: "2022-02-09",
								video: false,
								vote_average: 6.87,
								vote_count: 724,
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 7407,
						known_for_department: "Production",
						name: "Bradley Thomas",
						original_name: "Bradley Thomas",
						popularity: 4.074,
						profile_path: "/faE3s1dmajLR2qUxSs9e55I5j0M.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/riDYJYk4g8YnDjEgYOSSKzWTldq.jpg",
								id: 8467,
								title: "Dumb and Dumber",
								original_language: "en",
								original_title: "Dumb and Dumber",
								overview:
									'Lloyd and Harry are two men whose stupidity is really indescribable. When Mary, a beautiful woman, loses an important suitcase with money before she leaves for Aspen, the two friends (who have found the suitcase) decide to return it to her. After some "adventures" they finally get to Aspen where, using the lost money they live it up and fight for Mary\'s heart.',
								poster_path: "/4LdpBXiCyGKkR8FGHgjKlphrfUc.jpg",
								media_type: "movie",
								genre_ids: [35],
								popularity: 38.891,
								release_date: "1994-12-16",
								video: false,
								vote_average: 6.597,
								vote_count: 5378,
							},
							{
								adult: false,
								backdrop_path: "/egJQ3nIon5fT8wyXcKRHzvmtZpD.jpg",
								id: 544,
								title: "There's Something About Mary",
								original_language: "en",
								original_title: "There's Something About Mary",
								overview:
									"For Ted, prom night went about as bad as it’s possible for any night to go. Thirteen years later, he finally gets another chance with his old prom date, only to run up against other suitors including the sleazy detective he hired to find her.",
								poster_path: "/g03pwohXHOI75InM3zraiaEGguO.jpg",
								media_type: "movie",
								genre_ids: [10749, 35],
								popularity: 33.573,
								release_date: "1998-07-15",
								video: false,
								vote_average: 6.581,
								vote_count: 4408,
							},
							{
								adult: false,
								backdrop_path: "/mrgPeVDJEexgQ0UyqVyeJGvbefJ.jpg",
								id: 504172,
								title: "The Mule",
								original_language: "en",
								original_title: "The Mule",
								overview:
									"Earl Stone, a man in his eighties, is broke, alone, and facing foreclosure of his business when he is offered a job that simply requires him to drive. Easy enough, but, unbeknownst to Earl, he's just signed on as a drug courier for a Mexican cartel. He does so well that his cargo increases exponentially, and Earl hit the radar of hard-charging DEA agent Colin Bates.",
								poster_path: "/klazQbxk3yfuZ8JcfO9jdKOZQJ7.jpg",
								media_type: "movie",
								genre_ids: [80, 18, 53],
								popularity: 27.555,
								release_date: "2018-12-14",
								video: false,
								vote_average: 6.824,
								vote_count: 4411,
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 145151,
						known_for_department: "Acting",
						name: "Bradley Pierce",
						original_name: "Bradley Pierce",
						popularity: 4.463,
						profile_path: "/j6iW0vVA23GQniAPSYI6mi4hiEW.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/pYw10zrqfkdm3yD9JTO6vEGQhKy.jpg",
								id: 8844,
								title: "Jumanji",
								original_language: "en",
								original_title: "Jumanji",
								overview:
									"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures.",
								poster_path: "/vgpXmVaVyUL7GGiDeiK1mKEKzcX.jpg",
								media_type: "movie",
								genre_ids: [12, 14, 10751],
								popularity: 23.604,
								release_date: "1995-12-15",
								video: false,
								vote_average: 7.237,
								vote_count: 9495,
							},
							{
								adult: false,
								backdrop_path: "/jsgRkhPxYtzAhDFCUyNbvlX63tY.jpg",
								id: 10020,
								title: "Beauty and the Beast",
								original_language: "en",
								original_title: "Beauty and the Beast",
								overview:
									"Follow the adventures of Belle, a bright young woman who finds herself in the castle of a prince who's been turned into a mysterious beast. With the help of the castle's enchanted staff, Belle soon learns the most important lesson of all -- that true beauty comes from within.",
								poster_path: "/6DDJ8o2d6T4fpGWECLF4xBGTyAM.jpg",
								media_type: "movie",
								genre_ids: [10749, 10751, 16, 14],
								popularity: 100.957,
								release_date: "1991-10-22",
								video: false,
								vote_average: 7.731,
								vote_count: 8930,
							},
							{
								adult: false,
								backdrop_path: "/quYU0dRWsAHUY9DpIJqF0E3k91.jpg",
								id: 16690,
								title: "Return to Never Land",
								original_language: "en",
								original_title: "Return to Never Land",
								overview:
									"In 1940, the world is besieged by World War II. Wendy, all grown up, has two children; including Jane, who does not believe Wendy's stories about Peter Pan.",
								poster_path: "/y8TePNvpkId43hdFmZ6XvujVPl8.jpg",
								media_type: "movie",
								genre_ids: [12, 14, 16, 10751],
								popularity: 26.684,
								release_date: "2002-02-14",
								video: false,
								vote_average: 6.494,
								vote_count: 2155,
							},
						],
					},
					{
						adult: false,
						gender: 1,
						id: 1727374,
						known_for_department: "Acting",
						name: "Robyn Bradley",
						original_name: "Robyn Bradley",
						popularity: 4.141,
						profile_path: "/zNCNn6lfhNCj7UY5UWajEegUydZ.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/kiHblUfP8UopRyfKZONMMs7tfrE.jpg",
								id: 467956,
								title: "The Professor",
								original_language: "en",
								original_title: "The Professor",
								overview:
									"A world-weary college professor is given a life-changing diagnosis and decides to throw all pretense and conventions to the wind and live his life as boldly and freely as possible with a biting sense of humor, a reckless streak and a touch of madness.",
								poster_path: "/cypBSinhGuQaZ7VuOmGtcKMp91G.jpg",
								media_type: "movie",
								genre_ids: [35, 18],
								popularity: 15.141,
								release_date: "2018-05-17",
								video: false,
								vote_average: 6.85,
								vote_count: 949,
							},
							{
								adult: false,
								backdrop_path: "/nTk4rtSDIXkFEE2Bztq1iAlFDUU.jpg",
								id: 421626,
								title: "Sleigh Bells Ring",
								original_language: "en",
								original_title: "Sleigh Bells Ring",
								overview:
									"Recently divorced, Laurel struggles to get into the holiday spirit while heading up her hometown Christmas parade. With the help of a Christmas sleigh and a handsome woodworker, Laurel is destined to turn her luck around, rekindle her holiday spirit and even find time for love.",
								poster_path: "/60yNcrGKymskuN9OcO4BeNNn3q0.jpg",
								media_type: "movie",
								genre_ids: [10751, 10770, 10749],
								popularity: 3.947,
								release_date: "2016-12-18",
								video: false,
								vote_average: 6.1,
								vote_count: 39,
							},
							{
								adult: false,
								backdrop_path: "/mKV5bggK8jOfAEmxePlmvYbqn16.jpg",
								id: 737780,
								title: "Cross Country Christmas",
								original_language: "en",
								original_title: "Cross Country Christmas",
								overview:
									"Former classmates Lina and Max are traveling home for the holidays, until a storm hits and they have to work together to make it home in time, no matter the mode of transportation.",
								poster_path: "/lF5Bmfx8TZmDnNn8i7pSKA6zlEZ.jpg",
								media_type: "movie",
								genre_ids: [10770, 10749],
								popularity: 5.356,
								release_date: "2020-12-20",
								video: false,
								vote_average: 6.8,
								vote_count: 30,
							},
						],
					},
					{
						adult: false,
						gender: 1,
						id: 3069,
						known_for_department: "Acting",
						name: "Therese Bradley",
						original_name: "Therese Bradley",
						popularity: 3.319,
						profile_path: "/rkzXK3dRUd9n22RZHC22E130ieq.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/lnOTO53NazqQkUDiyK3WuU4ULef.jpg",
								id: 85889,
								title: "Filth",
								original_language: "en",
								original_title: "Filth",
								overview:
									"A bigoted junkie cop suffering from bipolar disorder and drug addiction manipulates and hallucinates his way through the festive season in a bid to secure promotion and win back his wife and daughter.",
								poster_path: "/wyB1WjlTPTM3I6lZip67GUzyrpS.jpg",
								media_type: "movie",
								genre_ids: [80, 18, 35],
								popularity: 12.781,
								release_date: "2013-09-23",
								video: false,
								vote_average: 6.872,
								vote_count: 1503,
							},
							{
								adult: false,
								backdrop_path: "/yVfhwgLBFDdI1LuaiFfA7y2FbVi.jpg",
								id: 474051,
								title: "Calibre",
								original_language: "en",
								original_title: "Calibre",
								overview:
									"Two lifelong friends head up to an isolated Scottish Highlands village for a weekend hunting trip that descends into a never-ending nightmare as they attempt to cover up a horrific hunting accident.",
								poster_path: "/gCVOQzV7Z556WnJFNeX7y8BFhyW.jpg",
								media_type: "movie",
								genre_ids: [53, 18],
								popularity: 13.469,
								release_date: "2018-06-22",
								video: false,
								vote_average: 6.47,
								vote_count: 554,
							},
							{
								adult: false,
								backdrop_path: "/10SM8QFBZjHwIjQ8uq7yZE8NGyf.jpg",
								id: 141043,
								title: "A Long Way Down",
								original_language: "en",
								original_title: "A Long Way Down",
								overview:
									"Four lost souls—a disgraced TV presenter, a foul-mouthed teen, an isolated single mother, and a solipsistic muso—decide to end their lives on the same night, New Year's Eve. When this disillusioned quartet of strangers meet unintentionally at the same suicide hotspot, a London high-rise with the well-earned nickname Topper's Tower, they mutually agree to call off their plans for six weeks, forming an unconventional, dysfunctional family. They become media sensations as the Topper House Four and search together for the reasons to keep on living.",
								poster_path: "/ibtYPDUQXKK2CIYzMEWgt1VNMlP.jpg",
								media_type: "movie",
								genre_ids: [35, 18],
								popularity: 11.959,
								release_date: "2014-03-20",
								video: false,
								vote_average: 6.2,
								vote_count: 801,
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 221723,
						known_for_department: "Directing",
						name: "Bradley Walsh",
						original_name: "Bradley Walsh",
						popularity: 5.484,
						profile_path: null,
						known_for: [
							{
								adult: false,
								backdrop_path: "/iobccQ0P5vs75rj33n2qbDKPN2Y.jpg",
								id: 555850,
								title: "The Holiday Calendar",
								original_language: "en",
								original_title: "The Holiday Calendar",
								overview:
									"A talented photographer stuck in a dead-end job inherits an antique Advent calendar that may be predicting the future -- and pointing her toward love.",
								poster_path: "/hiCeUExxUTGbU6FXORLf673uwvK.jpg",
								media_type: "movie",
								genre_ids: [10749, 35, 10751],
								popularity: 11.19,
								release_date: "2018-11-02",
								video: false,
								vote_average: 6.653,
								vote_count: 964,
							},
							{
								adult: false,
								backdrop_path: "/ombM2Yd0UORA7AlxXnIQ6ZFd8yE.jpg",
								id: 48865,
								name: "Reign",
								original_language: "en",
								original_name: "Reign",
								overview:
									"Mary, Queen of Scots, faces political and sexual intrigue in the treacherous world of the French court.",
								poster_path: "/epNfFs0gPyrpekecpzyX0XTkZgI.jpg",
								media_type: "tv",
								genre_ids: [18],
								popularity: 59.213,
								first_air_date: "2013-10-17",
								vote_average: 8.033,
								vote_count: 723,
								origin_country: ["US"],
							},
							{
								adult: false,
								backdrop_path: "/bdhFPMYxuG769gaOA7awyYpcGP.jpg",
								id: 58811,
								name: "Helix",
								original_language: "en",
								original_name: "Helix",
								overview:
									"Helix is an intense thriller about a team of scientists from the Centers for Disease Control who travel to a high-tech research facility in the Arctic to investigate a possible disease outbreak, only to find themselves pulled into a terrifying life-and-death struggle that holds the key to mankind's salvation...or total annihilation.",
								poster_path: "/7goT0IcsXjRo9fdMlWKr6ZRmaNP.jpg",
								media_type: "tv",
								genre_ids: [18, 10765],
								popularity: 26.081,
								first_air_date: "2014-01-10",
								vote_average: 6.709,
								vote_count: 354,
								origin_country: ["CA", "US"],
							},
						],
					},
					{
						adult: false,
						gender: 2,
						id: 129021,
						known_for_department: "Acting",
						name: "Bradley Dodds",
						original_name: "Bradley Dodds",
						popularity: 3.186,
						profile_path: "/qJ0MSSHqHua6FFTQZuEtLQ30j1v.jpg",
						known_for: [
							{
								adult: false,
								backdrop_path: "/nawzkUvXFv5J0Lwjw1OLwZGXLSA.jpg",
								id: 40264,
								title: "Vampires Suck",
								original_language: "en",
								original_title: "Vampires Suck",
								overview:
									"Becca, an anxious, non-vampire teen is torn between two boys. Before she can choose, Becca must get around her controlling father, who embarrasses Becca by treating her like a child. Meanwhile, Becca's friends contend with their own romantic issues - all of which collide at the prom.",
								poster_path: "/ksPKfoXovAiFnBktkCBefsRQ8a1.jpg",
								media_type: "movie",
								genre_ids: [35],
								popularity: 22.087,
								release_date: "2010-08-18",
								video: false,
								vote_average: 4.236,
								vote_count: 1101,
							},
							{
								adult: false,
								backdrop_path: "/ePE0OGjFM5ISufXhxoND9bJLzUH.jpg",
								id: 526266,
								title: "A Man For Every Month",
								original_language: "en",
								original_title: "A Man For Every Month",
								overview:
									"An shy writer has to go out on a date with a different man every month in order to write an article for her company's 'Man for Every Month' blog.",
								poster_path: "/41K5LkOeVH4Ui5uWgqoGxGPjRUY.jpg",
								media_type: "movie",
								genre_ids: [10749, 10751, 10770],
								popularity: 2.845,
								release_date: "2017-11-16",
								video: false,
								vote_average: 6.1,
								vote_count: 16,
							},
							{
								adult: false,
								backdrop_path: "/aE1FgGIvfcWfhip9lFosjGc94c4.jpg",
								id: 523900,
								title: "Spivak",
								original_language: "en",
								original_title: "Spivak",
								overview:
									"A self-loathing, failed Eastside novelist living in the ‘hipster’ neighborhood of Echo Park in Los Angeles is shocked to find himself falling in love with everything he hates, including a simple All-American blonde girl from the Westside.",
								poster_path: "/cngzHQUI0awWycL0XkYhCMEUPS9.jpg",
								media_type: "movie",
								genre_ids: [35],
								popularity: 4.471,
								release_date: "2018-05-11",
								video: false,
								vote_average: 5.6,
								vote_count: 21,
							},
						],
					},
				],
				total_pages: 67,
				total_results: 1336,
			});
		}
	}),
];
