export const movieID550DetailsMockResponse = {
  adult: false,
  backdrop_path: "/fCayJrkfRaCRCTh8GqN30f8oyQF.jpg",
  belongs_to_collection: null,
  budget: 63000000,
  genres: [
    {
      id: 18,
      name: "Drama",
    },
  ],
  homepage: "",
  id: 550,
  imdb_id: "tt0137523",
  original_language: "en",
  original_title: "Fight Club",
  overview:
    'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
  popularity: 0.5,
  poster_path: null,
  production_companies: [
    {
      id: 508,
      logo_path: "/7PzJdsLGlR7oW4J0J5Xcd0pHGRg.png",
      name: "Regency Enterprises",
      origin_country: "US",
    },
    {
      id: 711,
      logo_path: null,
      name: "Fox 2000 Pictures",
      origin_country: "",
    },
    {
      id: 20555,
      logo_path: null,
      name: "Taurus Film",
      origin_country: "",
    },
    {
      id: 54050,
      logo_path: null,
      name: "Linson Films",
      origin_country: "",
    },
    {
      id: 54051,
      logo_path: null,
      name: "Atman Entertainment",
      origin_country: "",
    },
    {
      id: 54052,
      logo_path: null,
      name: "Knickerbocker Films",
      origin_country: "",
    },
    {
      id: 25,
      logo_path: "/qZCc1lty5FzX30aOCVRBLzaVmcp.png",
      name: "20th Century Fox",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "1999-10-12",
  revenue: 100853753,
  runtime: 139,
  spoken_languages: [
    {
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Released",
  tagline:
    "How much can you know about yourself if you've never been in a fight?",
  title: "Fight Club",
  video: false,
  vote_average: 7.8,
  vote_count: 3439,
};

export const movieID603692DetailsMockResponse = {
  adult: false,
  backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
  belongs_to_collection: {
    id: 404609,
    name: "John Wick Collection",
    poster_path: "/xUidyvYFsbbuExifLkslpcd8SMc.jpg",
    backdrop_path: "/fSwYa5q2xRkBoOOjueLpkLf3N1m.jpg",
  },
  budget: 90000000,
  genres: [
    {
      id: 28,
      name: "Action",
    },
    {
      id: 53,
      name: "Thriller",
    },
    {
      id: 80,
      name: "Crime",
    },
  ],
  homepage: "https://johnwick.movie",
  id: 603692,
  imdb_id: "tt10366206",
  original_language: "en",
  original_title: "John Wick: Chapter 4",
  overview:
    "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
  popularity: 950.477,
  poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
  production_companies: [
    {
      id: 3528,
      logo_path: "/cCzCClIzIh81Fa79hpW5nXoUsHK.png",
      name: "Thunder Road",
      origin_country: "US",
    },
    {
      id: 23008,
      logo_path: "/5SarYupipdiejsEqUkwu1SpYfru.png",
      name: "87Eleven",
      origin_country: "US",
    },
    {
      id: 1632,
      logo_path: "/cisLn1YAUuptXVBa0xjq7ST9cH0.png",
      name: "Lionsgate",
      origin_country: "US",
    },
    {
      id: 491,
      logo_path: "/rUp0lLKa1pr4UsPm8fgzmnNGxtq.png",
      name: "Summit Entertainment",
      origin_country: "US",
    },
    {
      id: 195559,
      logo_path: "/fmh0UMCOa7JsDr6UhLESPePc3PE.png",
      name: "El-Torky Art Production",
      origin_country: "",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "2023-03-22",
  revenue: 0,
  runtime: 169,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
    {
      english_name: "French",
      iso_639_1: "fr",
      name: "Français",
    },
    {
      english_name: "Japanese",
      iso_639_1: "ja",
      name: "日本語",
    },
  ],
  status: "Released",
  tagline: "No way back, one way out.",
  title: "John Wick: Chapter 4",
  video: false,
  vote_average: 8.7,
  vote_count: 34,
};

export const personID287DetailsMockResponse = {
  birthday: "1963-12-18",
  known_for_department: "Acting",
  deathday: null,
  id: 287,
  name: "Brad Pitt",
  also_known_as: [
    "برد پیت",
    "Бред Питт",
    "Бред Пітт",
    "Buratto Pitto",
    "Брэд Питт",
    "畢·彼特",
    "ブラッド・ピット",
    "브래드 피트",
    "براد بيت",
    "แบรด พิตต์",
  ],
  gender: 2,
  biography:
    "William Bradley \"Brad\" Pitt (born December 18, 1963) is an American actor and film producer. Pitt has received two Academy Award nominations and four Golden Globe Award nominations, winning one. He has been described as one of the world's most attractive men, a label for which he has received substantial media attention. Pitt began his acting career with television guest appearances, including a role on the CBS prime-time soap opera Dallas in 1987. He later gained recognition as the cowboy hitchhiker who seduces Geena Davis's character in the 1991 road movie Thelma & Louise. Pitt's first leading roles in big-budget productions came with A River Runs Through It (1992) and Interview with the Vampire (1994). He was cast opposite Anthony Hopkins in the 1994 drama Legends of the Fall, which earned him his first Golden Globe nomination. In 1995 he gave critically acclaimed performances in the crime thriller Seven and the science fiction film 12 Monkeys, the latter securing him a Golden Globe Award for Best Supporting Actor and an Academy Award nomination.\n\nFour years later, in 1999, Pitt starred in the cult hit Fight Club. He then starred in the major international hit as Rusty Ryan in Ocean's Eleven (2001) and its sequels, Ocean's Twelve (2004) and Ocean's Thirteen (2007). His greatest commercial successes have been Troy (2004) and Mr. & Mrs. Smith (2005).\n\nPitt received his second Academy Award nomination for his title role performance in the 2008 film The Curious Case of Benjamin Button. Following a high-profile relationship with actress Gwyneth Paltrow, Pitt was married to actress Jennifer Aniston for five years. Pitt lives with actress Angelina Jolie in a relationship that has generated wide publicity. He and Jolie have six children—Maddox, Pax, Zahara, Shiloh, Knox, and Vivienne.\n\nSince beginning his relationship with Jolie, he has become increasingly involved in social issues both in the United States and internationally. Pitt owns a production company named Plan B Entertainment, whose productions include the 2007 Academy Award winning Best Picture, The Departed.",
  popularity: 10.647,
  place_of_birth: "Shawnee, Oklahoma, USA",
  profile_path: "/kU3B75TyRiCgE270EyZnHjfivoq.jpg",
  adult: false,
  imdb_id: "nm0000093",
  homepage: null,
};

export const searchByPersonMockResponse = {
  page: 1,
  results: [
    {
      adult: false,
      gender: 2,
      id: 51329,
      known_for_department: "Acting",
      name: "Bradley Cooper",
      original_name: "Bradley Cooper",
      popularity: 29.09,
      profile_path: "/DPnessSsWqVXRbKm93PtMjB4Us.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/2o0PKGmnSgCGkzoSePNAqse8Ure.jpg",
          id: 18785,
          title: "The Hangover",
          original_language: "en",
          original_title: "The Hangover",
          overview:
            "When three friends finally come to after a raucous night of bachelor-party revelry, they find a baby in the closet and a tiger in the bathroom. But they can't seem to locate their best friend, Doug – who's supposed to be tying the knot. Launching a frantic search for Doug, the trio perseveres through a nasty hangover to try to make it to the church on time.",
          poster_path: "/uluhlXubGu1VxU63X9VHCLWDAYP.jpg",
          media_type: "movie",
          genre_ids: [35],
          popularity: 116.515,
          release_date: "2009-06-02",
          video: false,
          vote_average: 7.309,
          vote_count: 15269,
        },
        {
          adult: false,
          backdrop_path: "/nrpivVyJjRQqVDhRTZWVPWqYwQp.jpg",
          id: 190859,
          title: "American Sniper",
          original_language: "en",
          original_title: "American Sniper",
          overview:
            "U.S. Navy SEAL Chris Kyle takes his sole mission—protect his comrades—to heart and becomes one of the most lethal snipers in American history. His pinpoint accuracy not only saves countless lives but also makes him a prime target of insurgents. Despite grave danger and his struggle to be a good husband and father to his family back in the States, Kyle serves four tours of duty in Iraq. However, when he finally returns home, he finds that he cannot leave the war behind.",
          poster_path: "/i1U46OwMc6vlm7OoSUKfqUH615e.jpg",
          media_type: "movie",
          genre_ids: [10752, 28],
          popularity: 94.213,
          release_date: "2014-12-25",
          video: false,
          vote_average: 7.433,
          vote_count: 11727,
        },
        {
          adult: false,
          backdrop_path: "/t5cuFKDgf5hRWYpRZ3jAANu5kPr.jpg",
          id: 82693,
          title: "Silver Linings Playbook",
          original_language: "en",
          original_title: "Silver Linings Playbook",
          overview:
            "After spending eight months in a mental institution, a former teacher moves back in with his parents and tries to reconcile with his ex-wife.",
          poster_path: "/y7iOVneBvITlBdhy6tVqXVOa1Js.jpg",
          media_type: "movie",
          genre_ids: [18, 35, 10749],
          popularity: 29.709,
          release_date: "2012-11-16",
          video: false,
          vote_average: 7.1,
          vote_count: 11007,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 94330,
      known_for_department: "Acting",
      name: "David Bradley",
      original_name: "David Bradley",
      popularity: 13.412,
      profile_path: "/uu275GxZrHfqcaBJx6DeSuHEYWy.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/pXqA3aUxrsdUbthRqBhnNUi0RVe.jpg",
          id: 25682,
          title: "American Ninja 3: Blood Hunt",
          original_language: "en",
          original_title: "American Ninja 3: Blood Hunt",
          overview:
            'Jackson is back, and now he has a new partner, karate champion Sean, as they must face a deadly terrorist known as "The Cobra", who has infected Sean with a virus. Sean and Jackson have no choice but to fight the Cobra and his bands of ninjas.',
          poster_path: "/oiKM4CAEXrhAfDkpnhBW8RpOQC7.jpg",
          media_type: "movie",
          genre_ids: [28, 12, 18],
          popularity: 9.636,
          release_date: "1989-02-24",
          video: false,
          vote_average: 4.669,
          vote_count: 136,
        },
        {
          adult: false,
          backdrop_path: "/6Y9Gd1GBge8LMV60xhk6XCUmNMI.jpg",
          id: 25684,
          title: "American Ninja 5",
          original_language: "en",
          original_title: "American Ninja 5",
          overview:
            "When a scientists daughter is kidnapped, American Ninja, attempts to find her, but this time he teams up with a youngster he has trained in the ways of the ninja.",
          poster_path: "/feLMfivbHHla844jWrVnqgzU0Zh.jpg",
          media_type: "movie",
          genre_ids: [28, 53],
          popularity: 10.254,
          release_date: "1993-01-01",
          video: false,
          vote_average: 4.719,
          vote_count: 96,
        },
        {
          adult: false,
          backdrop_path: "/lDtTiBO8CyLhbsi7idZe2MQDXTB.jpg",
          id: 25528,
          title: "American Ninja 4: The Annihilation",
          original_language: "en",
          original_title: "American Ninja 4: The Annihilation",
          overview:
            "The two American Ninjas, Joe Armstrong and Sean Davidson, team up to do battle against a terrorist and his band of Ninjas.",
          poster_path: "/3MoXMlTDQgpLr54veMT39rCyaTz.jpg",
          media_type: "movie",
          genre_ids: [28, 53],
          popularity: 11.404,
          release_date: "1990-10-30",
          video: false,
          vote_average: 5.226,
          vote_count: 124,
        },
      ],
    },
    {
      adult: false,
      gender: 2,
      id: 11180,
      known_for_department: "Acting",
      name: "David Bradley",
      original_name: "David Bradley",
      popularity: 14.376,
      profile_path: "/rDp3nmZTZIYokp3aSOzClpDkVlS.jpg",
      known_for: [
        {
          adult: false,
          backdrop_path: "/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
          id: 671,
          title: "Harry Potter and the Philosopher's Stone",
          original_language: "en",
          original_title: "Harry Potter and the Philosopher's Stone",
          overview:
            "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.",
          poster_path: "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
          media_type: "movie",
          genre_ids: [12, 14],
          popularity: 244.962,
          release_date: "2001-11-16",
          video: false,
          vote_average: 7.913,
          vote_count: 24426,
        },
        {
          adult: false,
          backdrop_path: "/urDWNffjwmNi5IQaezw9GwqkUXa.jpg",
          id: 767,
          title: "Harry Potter and the Half-Blood Prince",
          original_language: "en",
          original_title: "Harry Potter and the Half-Blood Prince",
          overview:
            "As Lord Voldemort tightens his grip on both the Muggle and wizarding worlds, Hogwarts is no longer a safe haven. Harry suspects perils may even lie within the castle, but Dumbledore is more intent upon preparing him for the final battle fast approaching. Together they work to find the key to unlock Voldemorts defenses and to this end, Dumbledore recruits his old friend and colleague Horace Slughorn, whom he believes holds crucial information. Even as the decisive showdown looms, romance blossoms for Harry, Ron, Hermione and their classmates. Love is in the air, but danger lies ahead and Hogwarts may never be the same again.",
          poster_path: "/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg",
          media_type: "movie",
          genre_ids: [12, 14],
          popularity: 209.35,
          release_date: "2009-07-07",
          video: false,
          vote_average: 7.699,
          vote_count: 17442,
        },
        {
          adult: false,
          backdrop_path: "/7tbeoSTWW2cWPecjQo9fcdf0Hzv.jpg",
          id: 672,
          title: "Harry Potter and the Chamber of Secrets",
          original_language: "en",
          original_title: "Harry Potter and the Chamber of Secrets",
          overview:
            "Cars fly, trees fight back, and a mysterious house-elf comes to warn Harry Potter at the start of his second year at Hogwarts. Adventure and danger await when bloody writing on a wall announces: The Chamber Of Secrets Has Been Opened. To save Hogwarts will require all of Harry, Ron and Hermione’s magical abilities and courage.",
          poster_path: "/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg",
          media_type: "movie",
          genre_ids: [12, 14],
          popularity: 227.355,
          release_date: "2002-11-13",
          video: false,
          vote_average: 7.723,
          vote_count: 19624,
        },
      ],
    },
  ],
  total_pages: 67,
  total_results: 1336,
};
