export const movieID550DetailsMockResponse = {
	adult: false,
	backdrop_path: "/fCayJrkfRaCRCTh8GqN30f8oyQF.jpg",
	belongs_to_collection: null,
	budget: 63000000,
	genres: [
		{
			id: 18,
			name: "Drama",
		},
	],
	homepage: "",
	id: 550,
	imdb_id: "tt0137523",
	original_language: "en",
	original_title: "Fight Club",
	overview:
		'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
	popularity: 0.5,
	poster_path: null,
	production_companies: [
		{
			id: 508,
			logo_path: "/7PzJdsLGlR7oW4J0J5Xcd0pHGRg.png",
			name: "Regency Enterprises",
			origin_country: "US",
		},
		{
			id: 711,
			logo_path: null,
			name: "Fox 2000 Pictures",
			origin_country: "",
		},
		{
			id: 20555,
			logo_path: null,
			name: "Taurus Film",
			origin_country: "",
		},
		{
			id: 54050,
			logo_path: null,
			name: "Linson Films",
			origin_country: "",
		},
		{
			id: 54051,
			logo_path: null,
			name: "Atman Entertainment",
			origin_country: "",
		},
		{
			id: 54052,
			logo_path: null,
			name: "Knickerbocker Films",
			origin_country: "",
		},
		{
			id: 25,
			logo_path: "/qZCc1lty5FzX30aOCVRBLzaVmcp.png",
			name: "20th Century Fox",
			origin_country: "US",
		},
	],
	production_countries: [
		{
			iso_3166_1: "US",
			name: "United States of America",
		},
	],
	release_date: "1999-10-12",
	revenue: 100853753,
	runtime: 139,
	spoken_languages: [
		{
			iso_639_1: "en",
			name: "English",
		},
	],
	status: "Released",
	tagline:
		"How much can you know about yourself if you've never been in a fight?",
	title: "Fight Club",
	video: false,
	vote_average: 7.8,
	vote_count: 3439,
};

export const movieID603692DetailsMockResponse = {
	adult: false,
	backdrop_path: "/h8gHn0OzBoaefsYseUByqsmEDMY.jpg",
	belongs_to_collection: {
		id: 404609,
		name: "John Wick Collection",
		poster_path: "/xUidyvYFsbbuExifLkslpcd8SMc.jpg",
		backdrop_path: "/fSwYa5q2xRkBoOOjueLpkLf3N1m.jpg",
	},
	budget: 90000000,
	genres: [
		{
			id: 28,
			name: "Action",
		},
		{
			id: 53,
			name: "Thriller",
		},
		{
			id: 80,
			name: "Crime",
		},
	],
	homepage: "https://johnwick.movie",
	id: 603692,
	imdb_id: "tt10366206",
	original_language: "en",
	original_title: "John Wick: Chapter 4",
	overview:
		"With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
	popularity: 950.477,
	poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
	production_companies: [
		{
			id: 3528,
			logo_path: "/cCzCClIzIh81Fa79hpW5nXoUsHK.png",
			name: "Thunder Road",
			origin_country: "US",
		},
		{
			id: 23008,
			logo_path: "/5SarYupipdiejsEqUkwu1SpYfru.png",
			name: "87Eleven",
			origin_country: "US",
		},
		{
			id: 1632,
			logo_path: "/cisLn1YAUuptXVBa0xjq7ST9cH0.png",
			name: "Lionsgate",
			origin_country: "US",
		},
		{
			id: 491,
			logo_path: "/rUp0lLKa1pr4UsPm8fgzmnNGxtq.png",
			name: "Summit Entertainment",
			origin_country: "US",
		},
		{
			id: 195559,
			logo_path: "/fmh0UMCOa7JsDr6UhLESPePc3PE.png",
			name: "El-Torky Art Production",
			origin_country: "",
		},
	],
	production_countries: [
		{
			iso_3166_1: "US",
			name: "United States of America",
		},
	],
	release_date: "2023-03-22",
	revenue: 0,
	runtime: 169,
	spoken_languages: [
		{
			english_name: "English",
			iso_639_1: "en",
			name: "English",
		},
		{
			english_name: "French",
			iso_639_1: "fr",
			name: "Français",
		},
		{
			english_name: "Japanese",
			iso_639_1: "ja",
			name: "日本語",
		},
	],
	status: "Released",
	tagline: "No way back, one way out.",
	title: "John Wick: Chapter 4",
	video: false,
	vote_average: 8.7,
	vote_count: 34,
};

export const personID287DetailsMockResponse = {
	birthday: "1963-12-18",
	known_for_department: "Acting",
	deathday: null,
	id: 287,
	name: "Brad Pitt",
	also_known_as: [
		"برد پیت",
		"Бред Питт",
		"Бред Пітт",
		"Buratto Pitto",
		"Брэд Питт",
		"畢·彼特",
		"ブラッド・ピット",
		"브래드 피트",
		"براد بيت",
		"แบรด พิตต์",
	],
	gender: 2,
	biography:
		"William Bradley \"Brad\" Pitt (born December 18, 1963) is an American actor and film producer. Pitt has received two Academy Award nominations and four Golden Globe Award nominations, winning one. He has been described as one of the world's most attractive men, a label for which he has received substantial media attention. Pitt began his acting career with television guest appearances, including a role on the CBS prime-time soap opera Dallas in 1987. He later gained recognition as the cowboy hitchhiker who seduces Geena Davis's character in the 1991 road movie Thelma & Louise. Pitt's first leading roles in big-budget productions came with A River Runs Through It (1992) and Interview with the Vampire (1994). He was cast opposite Anthony Hopkins in the 1994 drama Legends of the Fall, which earned him his first Golden Globe nomination. In 1995 he gave critically acclaimed performances in the crime thriller Seven and the science fiction film 12 Monkeys, the latter securing him a Golden Globe Award for Best Supporting Actor and an Academy Award nomination.\n\nFour years later, in 1999, Pitt starred in the cult hit Fight Club. He then starred in the major international hit as Rusty Ryan in Ocean's Eleven (2001) and its sequels, Ocean's Twelve (2004) and Ocean's Thirteen (2007). His greatest commercial successes have been Troy (2004) and Mr. & Mrs. Smith (2005).\n\nPitt received his second Academy Award nomination for his title role performance in the 2008 film The Curious Case of Benjamin Button. Following a high-profile relationship with actress Gwyneth Paltrow, Pitt was married to actress Jennifer Aniston for five years. Pitt lives with actress Angelina Jolie in a relationship that has generated wide publicity. He and Jolie have six children—Maddox, Pax, Zahara, Shiloh, Knox, and Vivienne.\n\nSince beginning his relationship with Jolie, he has become increasingly involved in social issues both in the United States and internationally. Pitt owns a production company named Plan B Entertainment, whose productions include the 2007 Academy Award winning Best Picture, The Departed.",
	popularity: 10.647,
	place_of_birth: "Shawnee, Oklahoma, USA",
	profile_path: "/kU3B75TyRiCgE270EyZnHjfivoq.jpg",
	adult: false,
	imdb_id: "nm0000093",
	homepage: null,
};

export const searchByPersonMockResponse = {
	page: 1,
	results: [
		{
			adult: false,
			gender: 2,
			id: 51329,
			known_for_department: "Acting",
			name: "Bradley Cooper",
			original_name: "Bradley Cooper",
			popularity: 29.09,
			profile_path: "/DPnessSsWqVXRbKm93PtMjB4Us.jpg",
			known_for: [
				{
					adult: false,
					backdrop_path: "/2o0PKGmnSgCGkzoSePNAqse8Ure.jpg",
					id: 18785,
					title: "The Hangover",
					original_language: "en",
					original_title: "The Hangover",
					overview:
						"When three friends finally come to after a raucous night of bachelor-party revelry, they find a baby in the closet and a tiger in the bathroom. But they can't seem to locate their best friend, Doug – who's supposed to be tying the knot. Launching a frantic search for Doug, the trio perseveres through a nasty hangover to try to make it to the church on time.",
					poster_path: "/uluhlXubGu1VxU63X9VHCLWDAYP.jpg",
					media_type: "movie",
					genre_ids: [35],
					popularity: 116.515,
					release_date: "2009-06-02",
					video: false,
					vote_average: 7.309,
					vote_count: 15269,
				},
				{
					adult: false,
					backdrop_path: "/nrpivVyJjRQqVDhRTZWVPWqYwQp.jpg",
					id: 190859,
					title: "American Sniper",
					original_language: "en",
					original_title: "American Sniper",
					overview:
						"U.S. Navy SEAL Chris Kyle takes his sole mission—protect his comrades—to heart and becomes one of the most lethal snipers in American history. His pinpoint accuracy not only saves countless lives but also makes him a prime target of insurgents. Despite grave danger and his struggle to be a good husband and father to his family back in the States, Kyle serves four tours of duty in Iraq. However, when he finally returns home, he finds that he cannot leave the war behind.",
					poster_path: "/i1U46OwMc6vlm7OoSUKfqUH615e.jpg",
					media_type: "movie",
					genre_ids: [10752, 28],
					popularity: 94.213,
					release_date: "2014-12-25",
					video: false,
					vote_average: 7.433,
					vote_count: 11727,
				},
				{
					adult: false,
					backdrop_path: "/t5cuFKDgf5hRWYpRZ3jAANu5kPr.jpg",
					id: 82693,
					title: "Silver Linings Playbook",
					original_language: "en",
					original_title: "Silver Linings Playbook",
					overview:
						"After spending eight months in a mental institution, a former teacher moves back in with his parents and tries to reconcile with his ex-wife.",
					poster_path: "/y7iOVneBvITlBdhy6tVqXVOa1Js.jpg",
					media_type: "movie",
					genre_ids: [18, 35, 10749],
					popularity: 29.709,
					release_date: "2012-11-16",
					video: false,
					vote_average: 7.1,
					vote_count: 11007,
				},
			],
		},
		{
			adult: false,
			gender: 2,
			id: 94330,
			known_for_department: "Acting",
			name: "David Bradley",
			original_name: "David Bradley",
			popularity: 13.412,
			profile_path: "/uu275GxZrHfqcaBJx6DeSuHEYWy.jpg",
			known_for: [
				{
					adult: false,
					backdrop_path: "/pXqA3aUxrsdUbthRqBhnNUi0RVe.jpg",
					id: 25682,
					title: "American Ninja 3: Blood Hunt",
					original_language: "en",
					original_title: "American Ninja 3: Blood Hunt",
					overview:
						'Jackson is back, and now he has a new partner, karate champion Sean, as they must face a deadly terrorist known as "The Cobra", who has infected Sean with a virus. Sean and Jackson have no choice but to fight the Cobra and his bands of ninjas.',
					poster_path: "/oiKM4CAEXrhAfDkpnhBW8RpOQC7.jpg",
					media_type: "movie",
					genre_ids: [28, 12, 18],
					popularity: 9.636,
					release_date: "1989-02-24",
					video: false,
					vote_average: 4.669,
					vote_count: 136,
				},
				{
					adult: false,
					backdrop_path: "/6Y9Gd1GBge8LMV60xhk6XCUmNMI.jpg",
					id: 25684,
					title: "American Ninja 5",
					original_language: "en",
					original_title: "American Ninja 5",
					overview:
						"When a scientists daughter is kidnapped, American Ninja, attempts to find her, but this time he teams up with a youngster he has trained in the ways of the ninja.",
					poster_path: "/feLMfivbHHla844jWrVnqgzU0Zh.jpg",
					media_type: "movie",
					genre_ids: [28, 53],
					popularity: 10.254,
					release_date: "1993-01-01",
					video: false,
					vote_average: 4.719,
					vote_count: 96,
				},
				{
					adult: false,
					backdrop_path: "/lDtTiBO8CyLhbsi7idZe2MQDXTB.jpg",
					id: 25528,
					title: "American Ninja 4: The Annihilation",
					original_language: "en",
					original_title: "American Ninja 4: The Annihilation",
					overview:
						"The two American Ninjas, Joe Armstrong and Sean Davidson, team up to do battle against a terrorist and his band of Ninjas.",
					poster_path: "/3MoXMlTDQgpLr54veMT39rCyaTz.jpg",
					media_type: "movie",
					genre_ids: [28, 53],
					popularity: 11.404,
					release_date: "1990-10-30",
					video: false,
					vote_average: 5.226,
					vote_count: 124,
				},
			],
		},
		{
			adult: false,
			gender: 2,
			id: 11180,
			known_for_department: "Acting",
			name: "David Bradley",
			original_name: "David Bradley",
			popularity: 14.376,
			profile_path: "/rDp3nmZTZIYokp3aSOzClpDkVlS.jpg",
			known_for: [
				{
					adult: false,
					backdrop_path: "/hziiv14OpD73u9gAak4XDDfBKa2.jpg",
					id: 671,
					title: "Harry Potter and the Philosopher's Stone",
					original_language: "en",
					original_title: "Harry Potter and the Philosopher's Stone",
					overview:
						"Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.",
					poster_path: "/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
					media_type: "movie",
					genre_ids: [12, 14],
					popularity: 244.962,
					release_date: "2001-11-16",
					video: false,
					vote_average: 7.913,
					vote_count: 24426,
				},
				{
					adult: false,
					backdrop_path: "/urDWNffjwmNi5IQaezw9GwqkUXa.jpg",
					id: 767,
					title: "Harry Potter and the Half-Blood Prince",
					original_language: "en",
					original_title: "Harry Potter and the Half-Blood Prince",
					overview:
						"As Lord Voldemort tightens his grip on both the Muggle and wizarding worlds, Hogwarts is no longer a safe haven. Harry suspects perils may even lie within the castle, but Dumbledore is more intent upon preparing him for the final battle fast approaching. Together they work to find the key to unlock Voldemorts defenses and to this end, Dumbledore recruits his old friend and colleague Horace Slughorn, whom he believes holds crucial information. Even as the decisive showdown looms, romance blossoms for Harry, Ron, Hermione and their classmates. Love is in the air, but danger lies ahead and Hogwarts may never be the same again.",
					poster_path: "/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg",
					media_type: "movie",
					genre_ids: [12, 14],
					popularity: 209.35,
					release_date: "2009-07-07",
					video: false,
					vote_average: 7.699,
					vote_count: 17442,
				},
				{
					adult: false,
					backdrop_path: "/7tbeoSTWW2cWPecjQo9fcdf0Hzv.jpg",
					id: 672,
					title: "Harry Potter and the Chamber of Secrets",
					original_language: "en",
					original_title: "Harry Potter and the Chamber of Secrets",
					overview:
						"Cars fly, trees fight back, and a mysterious house-elf comes to warn Harry Potter at the start of his second year at Hogwarts. Adventure and danger await when bloody writing on a wall announces: The Chamber Of Secrets Has Been Opened. To save Hogwarts will require all of Harry, Ron and Hermione’s magical abilities and courage.",
					poster_path: "/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg",
					media_type: "movie",
					genre_ids: [12, 14],
					popularity: 227.355,
					release_date: "2002-11-13",
					video: false,
					vote_average: 7.723,
					vote_count: 19624,
				},
			],
		},
	],
	total_pages: 67,
	total_results: 1336,
};

export const searchKeywordMockResponse = {
	page: 1,
	results: [
		{
			adult: false,
			backdrop_path: "/nL9SNohJaUQObVO3LyvDQbaC0jm.jpg",
			id: 119884,
			title: "Arnold",
			original_language: "en",
			original_title: "Arnold",
			overview:
				"Karen marries Arnold at his funeral and continues to get his money as long as she stays by his coffin. Meanwhile, various oddball relatives after Arnold's wealth are being killed in a creative variety of ways.",
			poster_path: "/eqlGD4RRiElW9OIvqupEfUBfRXj.jpg",
			media_type: "movie",
			genre_ids: [53, 27, 35, 9648],
			popularity: 2.191,
			release_date: "1973-11-16",
			video: false,
			vote_average: 4.708,
			vote_count: 12,
		},
		{
			adult: false,
			backdrop_path: null,
			id: 803975,
			title: "Arnold",
			original_language: "en",
			original_title: "Arnold",
			overview:
				"Arnold accidentally knocks out a bully named Harold during a baseball game, and Harold gives Arnold 24 hours to live before he beats him to a pulp.  Theatrical short pilot of Hey Arnold.",
			poster_path: "/gkjGv864BJfzMX5RjX6bX4CR1c2.jpg",
			media_type: "movie",
			genre_ids: [16],
			popularity: 0.6,
			release_date: "1996-07-10",
			video: false,
			vote_average: 10.0,
			vote_count: 1,
		},
	],
	total_pages: 70,
	total_results: 1383,
};

export const personID119589SocialMediaMockResponse = {
	id: 119589,
	freebase_mid: "/m/02778wm",
	freebase_id: "/en/donald_glover",
	imdb_id: "nm2255973",
	tvrage_id: null,
	wikidata_id: "Q1239933",
	facebook_id: "donaldglover",
	instagram_id: "childishgambino",
	tiktok_id: null,
	twitter_id: "donaldglover",
	youtube_id: null,
};

export const personID119589DetailsMockResponse = {
	adult: false,
	also_known_as: ["Childish Gambino"],
	biography:
		"Donald McKinley Glover Jr. (born September 25, 1983), also known by the stage name Childish Gambino, is an American actor, rapper, singer, writer, comedian, director, and producer. After working on Derrick Comedy while studying at New York University, Glover was hired at age 23 by Tina Fey as a writer for the NBC sitcom 30 Rock. He later rose to fame for portraying college student Troy Barnes on the NBC sitcom Community from 2009 to 2014. Since 2016, Glover stars in the FX series Atlanta, which he created and occasionally directs. For his work on Atlanta, Glover won various accolades, including two Primetime Emmy Awards and two Golden Globe Awards.\n\nGlover has starred in several successful films, including the supernatural horror The Lazarus Effect (2015), the comedy-drama Magic Mike XXL (2015), and science fiction film The Martian (2015). He played Aaron Davis in the superhero film Spider-Man: Homecoming (2017), and played Lando Calrissian in the Space Western Solo: A Star Wars Story (2018). He also provided the voice of adult Simba in The Lion King (2019). A filmmaker, Glover starred in and produced the short film Guava Island (2019).",
	birthday: "1983-09-25",
	deathday: null,
	gender: 2,
	homepage: null,
	id: 119589,
	imdb_id: "nm2255973",
	known_for_department: "Acting",
	name: "Donald Glover",
	place_of_birth: "Stone Mountain, Georgia, USA",
	popularity: 11.765,
	profile_path: "/jqVkQfeeEmdga1G0jpBwwXXwwSK.jpg",
};

export const personID119589PopMoviesMockResponse = {
	page: 1,
	results: [
		{
			adult: false,
			backdrop_path: "/1TUg5pO1VZ4B0Q1amk3OlXvlpXV.jpg",
			genre_ids: [12, 18, 10751],
			id: 420818,
			original_language: "en",
			original_title: "The Lion King",
			overview:
				"Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub's arrival. Scar, Mufasa's brother—and former heir to the throne—has plans of his own. The battle for Pride Rock is ravaged with betrayal, tragedy and drama, ultimately resulting in Simba's exile. With help from a curious pair of newfound friends, Simba will have to figure out how to grow up and take back what is rightfully his.",
			popularity: 116.645,
			poster_path: "/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg",
			release_date: "2019-07-12",
			title: "The Lion King",
			video: false,
			vote_average: 7.1,
			vote_count: 9014,
		},
		{
			adult: false,
			backdrop_path: "/tTlAA0REGPXSZPBfWyTW9ipIv1I.jpg",
			genre_ids: [28, 12, 878, 18],
			id: 315635,
			original_language: "en",
			original_title: "Spider-Man: Homecoming",
			overview:
				"Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
			popularity: 112.446,
			poster_path: "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
			release_date: "2017-07-05",
			title: "Spider-Man: Homecoming",
			video: false,
			vote_average: 7.4,
			vote_count: 19804,
		},
		{
			adult: false,
			backdrop_path: "/3dPhs7hUnQLphDFzdkD407VZDYo.jpg",
			genre_ids: [18, 12, 878],
			id: 286217,
			original_language: "en",
			original_title: "The Martian",
			overview:
				"During a manned mission to Mars, Astronaut Mark Watney is presumed dead after a fierce storm and left behind by his crew. But Watney has survived and finds himself stranded and alone on the hostile planet. With only meager supplies, he must draw upon his ingenuity, wit and spirit to subsist and find a way to signal to Earth that he is alive.",
			popularity: 49.354,
			poster_path: "/5BHuvQ6p9kfc091Z8RiFNhCwL4b.jpg",
			release_date: "2015-09-30",
			title: "The Martian",
			video: false,
			vote_average: 7.7,
			vote_count: 17953,
		},
		{
			adult: false,
			backdrop_path: "/ojHCeDULAkQK25700fhRU75Tur2.jpg",
			genre_ids: [878, 12, 28],
			id: 348350,
			original_language: "en",
			original_title: "Solo: A Star Wars Story",
			overview:
				"Through a series of daring escapades deep within a dark and dangerous criminal underworld, Han Solo meets his mighty future copilot Chewbacca and encounters the notorious gambler Lando Calrissian.",
			popularity: 39.209,
			poster_path: "/3IGbjc5ZC5yxim5W0sFING2kdcz.jpg",
			release_date: "2018-05-15",
			title: "Solo: A Star Wars Story",
			video: false,
			vote_average: 6.6,
			vote_count: 7593,
		},
		{
			adult: false,
			backdrop_path: "/2FYzxgLNuNVwncilzUeCGbOQzP7.jpg",
			genre_ids: [35, 878, 28],
			id: 479455,
			original_language: "en",
			original_title: "Men in Black: International",
			overview:
				"The Men in Black have always protected the Earth from the scum of the universe. In this new adventure, they tackle their biggest, most global threat to date: a mole in the Men in Black organization.",
			popularity: 36.287,
			poster_path: "/dPrUPFcgLfNbmDL8V69vcrTyEfb.jpg",
			release_date: "2019-06-12",
			title: "Men in Black: International",
			video: false,
			vote_average: 6,
			vote_count: 4280,
		},
		{
			adult: false,
			backdrop_path: "/tObVe1R7JnO3VXBvAOWTEPmmegu.jpg",
			genre_ids: [99],
			id: 961651,
			original_language: "en",
			original_title: "Spider-Man: All Roads Lead to No Way Home",
			overview:
				"Join our hosts JB Smoove and Martin Starr for a celebration of 20 years of Spider-Man™ movies!  From the original Sam Raimi trilogy to Marc Webb’s “amazing” movies to the latest trio from Director Jon Watts, we will take viewers through the stars, the stunts and action, the villains and heroes and an homage to Stan Lee, along with a few surprises. Find your favourite Spider-Man pajamas and prepare to swing through the past two decades of Spider-Man at the movies!",
			popularity: 35.784,
			poster_path: "/e2LLmI5wKIrWGAy9Of3yyWu7Szn.jpg",
			release_date: "2022-05-03",
			title: "Spider-Man: All Roads Lead to No Way Home",
			video: false,
			vote_average: 7.1,
			vote_count: 30,
		},
		{
			adult: false,
			backdrop_path: "/4CLjQROBGWpeiLK8DgMSxHHW9Wa.jpg",
			genre_ids: [35, 18],
			id: 264999,
			original_language: "en",
			original_title: "Magic Mike XXL",
			overview:
				"Three years after Mike bowed out of the stripper life at the top of his game, he and the remaining Kings of Tampa hit the road to Myrtle Beach to put on one last blow-out performance.",
			popularity: 31.756,
			poster_path: "/mXWbLqTWziO9aAyWMBzVnDSP57t.jpg",
			release_date: "2015-07-01",
			title: "Magic Mike XXL",
			video: false,
			vote_average: 6.2,
			vote_count: 1616,
		},
		{
			adult: false,
			backdrop_path: "/ysHWeVWSQZCIEBSEVf1nPddRn58.jpg",
			genre_ids: [35, 10402],
			id: 64328,
			original_language: "en",
			original_title: "The Muppets",
			overview:
				"When Kermit the Frog and the Muppets learn that their beloved theater is slated for demolition, a sympathetic human, Gary, and his puppet brother, Walter, swoop in to help the gang put on a show and raise the $10 million they need to save the day.",
			popularity: 22.589,
			poster_path: "/rsNbxonO8gtylIXwiv7JeqwJ4Kb.jpg",
			release_date: "2011-11-22",
			title: "The Muppets",
			video: false,
			vote_average: 6.7,
			vote_count: 1369,
		},
		{
			adult: false,
			backdrop_path: "/rBp2fDHV743C5hS94Ckij3vdDIh.jpg",
			genre_ids: [35, 10749],
			id: 129139,
			original_language: "en",
			original_title: "The To Do List",
			overview:
				"Feeling pressured to become more sexually experienced before she goes to college, Brandy Klark makes a list of things to accomplish before hitting campus in the fall.",
			popularity: 18.449,
			poster_path: "/r8OYOeiSyC2CmogqfRAMCUc0Xfc.jpg",
			release_date: "2013-07-24",
			title: "The To Do List",
			video: false,
			vote_average: 5.7,
			vote_count: 910,
		},
		{
			adult: false,
			backdrop_path: "/rmATIGQeSJZn0mSJZVluV4unkWZ.jpg",
			genre_ids: [10751, 35],
			id: 218778,
			original_language: "en",
			original_title:
				"Alexander and the Terrible, Horrible, No Good, Very Bad Day",
			overview:
				"Alexander's day begins with gum stuck in his hair, followed by more calamities. Though he finds little sympathy from his family and begins to wonder if bad things only happen to him, his mom, dad, brother, and sister all find themselves living through their own terrible, horrible, no good, very bad day.",
			popularity: 13.134,
			poster_path: "/7BVEl2hP21VZ1ymsXlCeoH1fBG8.jpg",
			release_date: "2014-10-08",
			title: "Alexander and the Terrible, Horrible, No Good, Very Bad Day",
			video: false,
			vote_average: 6.2,
			vote_count: 1206,
		},
		{
			adult: false,
			backdrop_path: "/1zfWZyaoRQOKSSCbyWMxZRZWZVa.jpg",
			genre_ids: [27, 53, 9648, 878],
			id: 243940,
			original_language: "en",
			original_title: "The Lazarus Effect",
			overview:
				"Medical researcher Frank, his fiancee Zoe and their team have achieved the impossible: they have found a way to revive the dead. After a successful, but unsanctioned, experiment on a lifeless animal, they are ready to make their work public. However, when their dean learns what they've done, he shuts them down. Zoe is killed during an attempt to recreate the experiment, leading Frank to test the process on her. Zoe is revived -- but something evil is within her.",
			popularity: 12.062,
			poster_path: "/4aq0TOLvITU3iWRUfxlRc83lMz1.jpg",
			release_date: "2015-01-29",
			title: "The Lazarus Effect",
			video: false,
			vote_average: 5.3,
			vote_count: 1265,
		},
		{
			adult: false,
			backdrop_path: "/5WanYc1TXD0BxEgEXs3S4ervdoZ.jpg",
			genre_ids: [10402, 99],
			id: 896633,
			original_language: "en",
			original_title: "Adele One Night Only",
			overview:
				"A primetime special with performances from the superstar including Adele’s first new material in six years plus her chart-topping hits. The special will also feature an exclusive interview with Adele by Oprah Winfrey from her rose garden, in Adele’s first televised wide-ranging conversation.",
			popularity: 11.029,
			poster_path: "/A7tO3IHm02FqRvE4R78bDkYX1Al.jpg",
			release_date: "2021-11-14",
			title: "Adele One Night Only",
			video: false,
			vote_average: 8.2,
			vote_count: 40,
		},
		{
			adult: false,
			backdrop_path: "/iyiLSQlJ6vbqEHdabO8wDF4aS1W.jpg",
			genre_ids: [35, 53],
			id: 543343,
			original_language: "en",
			original_title: "Guava Island",
			overview:
				"Deni Maroon, a musician and dock worker is determined to pull off a music festival against the interests of the local factory owner.",
			popularity: 9.614,
			poster_path: "/oQ5OnvNNGUYOPh3iTjmqx6GPsdc.jpg",
			release_date: "2019-04-13",
			title: "Guava Island",
			video: false,
			vote_average: 6.7,
			vote_count: 285,
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [35, 878, 16, 10770],
			id: 51888,
			original_language: "en",
			original_title: "Robot Chicken: Star Wars Episode III",
			overview:
				"Robot Chicken: Star Wars Episode III, directed by Chris McKay, combines the satirical sensibilities of Green and Matthew Senreich's Robot Chicken with characters of the Star Wars universe.",
			popularity: 7.55,
			poster_path: "/mi2lVho2zpfwcxI6yC1QYJi435D.jpg",
			release_date: "2010-12-19",
			title: "Robot Chicken: Star Wars Episode III",
			video: false,
			vote_average: 7.4,
			vote_count: 125,
		},
		{
			adult: false,
			backdrop_path: "/lB8aSbmrqwXe1ik4FbLKvVCySPs.jpg",
			genre_ids: [99],
			id: 253292,
			original_language: "en",
			original_title: "Harmontown",
			overview:
				"A comedic, brutally honest documentary following self-destructive TV writer Dan Harmon (NBC's Community) as he takes his live podcast on a national tour.",
			popularity: 6.965,
			poster_path: "/5HlxDzy3LZ26r5as5pLX7jYVcyC.jpg",
			release_date: "2014-03-08",
			title: "Harmontown",
			video: false,
			vote_average: 6.7,
			vote_count: 72,
		},
		{
			adult: false,
			backdrop_path: null,
			genre_ids: [35, 80, 9648, 53],
			id: 38087,
			original_language: "en",
			original_title: "Mystery Team",
			overview:
				"A group of former Encyclopedia Brown-style child-detectives struggle to solve an adult mystery.",
			popularity: 6.031,
			poster_path: "/npi5W12mH4HTXzCoYnRzRtrnIhP.jpg",
			release_date: "2009-08-28",
			title: "Mystery Team",
			video: false,
			vote_average: 6.3,
			vote_count: 125,
		},
		{
			adult: false,
			backdrop_path: "/xGbK1ZBVdRMnNK4y23SCquAJSdI.jpg",
			genre_ids: [10402, 99],
			id: 83589,
			original_language: "en",
			original_title: "Shut Up and Play the Hits",
			overview:
				"An intimate portrait of Brooklyn-based electronic rock band LCD Soundsystem's then-final live show on April 2, 2011, capturing both the exuberant, three-hour farewell concert at New York City's Madison Square Garden and frontman James Murphy's introspective 48 hours surrounding it.",
			popularity: 4.475,
			poster_path: "/8e5f9fMU1FtWPmZZTrvqk3hCG81.jpg",
			release_date: "2012-01-22",
			title: "Shut Up and Play the Hits",
			video: false,
			vote_average: 7,
			vote_count: 42,
		},
		{
			adult: false,
			backdrop_path: "/atXmDCUmfXi3l8zlfzz49RX6Txa.jpg",
			genre_ids: [35],
			id: 84154,
			original_language: "en",
			original_title: "Donald Glover: Weirdo",
			overview:
				'Fearlessly funny stand-up comic and sitcom star Donald Glover puts on a live show in New York, confessing his love for Cocoa Puffs and Toys "R" Us.',
			popularity: 4.033,
			poster_path: "/yWNAh2aJ4pgXXrC926gtOoeWam.jpg",
			release_date: "2012-01-18",
			title: "Donald Glover: Weirdo",
			video: false,
			vote_average: 6.9,
			vote_count: 63,
		},
		{
			adult: false,
			backdrop_path: "/ntvfsI2M9qy4yrlhBdCWRbNgPIc.jpg",
			genre_ids: [10402],
			id: 25150,
			original_language: "en",
			original_title: "Awesome; I Fuckin' Shot That!",
			overview:
				"Awesome; I Fuckin' Shot That! is a 2006 concert film of the Beastie Boys. It was created by giving camcorders to 50 audience members of a sold out concert at Madison Square Garden on October 9, 2004. The audience members were instructed to keep the cameras rolling at all times. The DVD of this concert movie was released on July 24, 2006 in the UK and July 25, 2006 in the US.",
			popularity: 3.557,
			poster_path: "/dCmuAPayMSAK51Dl6xZBSAL5yh0.jpg",
			release_date: "2006-03-31",
			title: "Awesome; I Fuckin' Shot That!",
			video: false,
			vote_average: 6.8,
			vote_count: 16,
		},
		{
			adult: false,
			backdrop_path: "/lwwnoNDP7xEP2xypd0knp6zY8Cg.jpg",
			genre_ids: [10751, 14, 10402],
			id: 702920,
			original_language: "en",
			original_title: "The Disney Family Singalong - Volume II",
			overview:
				"Ryan Seacrest hosts the second Disney Family Singalong featuring celebrities and their families as they take on their favorite Disney tunes from their homes. Special guests include John Legend, Christina Aguilera, Shakira, and Katy Perry.",
			popularity: 2.561,
			poster_path: "/uOYIKG0RfK6iWGQQXXY2vEHA7gI.jpg",
			release_date: "2020-05-10",
			title: "The Disney Family Singalong - Volume II",
			video: false,
			vote_average: 7.9,
			vote_count: 8,
		},
	],
	total_pages: 2,
	total_results: 28,
};

export const movieID420818VideoMockResponse = {
	id: 420818,
	results: [
		{
			iso_639_1: "en",
			iso_3166_1: "US",
			name: '"Circle of Life" Clip | The Lion King',
			key: "46x7PRyNL3Q",
			site: "YouTube",
			size: 1080,
			type: "Clip",
			official: true,
			published_at: "2019-08-01T17:04:26.000Z",
			id: "5e8fe98615959f0012ed082c",
		},
		{
			iso_639_1: "en",
			iso_3166_1: "US",
			name: '"We\'re Gonna Name Him Fred" Clip | The Lion King',
			key: "7i0K81zqHyI",
			site: "YouTube",
			size: 1080,
			type: "Clip",
			official: true,
			published_at: "2019-07-19T12:00:01.000Z",
			id: "5e8fe96700fb6b0013a08d82",
		},
		{
			iso_639_1: "en",
			iso_3166_1: "US",
			name: "The Lion King Movie Clip - Find Your Roar (2019) | Movieclips Coming Soon",
			key: "1JSw28el5Q4",
			site: "YouTube",
			size: 1080,
			type: "Clip",
			official: false,
			published_at: "2019-07-10T21:18:20.000Z",
			id: "5e8fe9c100fb6b001aa08993",
		},
		{
			iso_639_1: "en",
			iso_3166_1: "US",
			name: 'The Lion King - "Circle of Life" Official Teaser Trailer',
			key: "CA-gC-PaF48",
			site: "YouTube",
			size: 1080,
			type: "Teaser",
			official: false,
			published_at: "2019-07-10T18:17:00.000Z",
			id: "5d2632d0a698cf0010acf6e0",
		},
		{
			iso_639_1: "en",
			iso_3166_1: "US",
			name: '"The King Returns" Featurette | The Lion King',
			key: "flXkOTJBtvU",
			site: "YouTube",
			size: 1080,
			type: "Featurette",
			official: true,
			published_at: "2019-07-02T16:00:09.000Z",
			id: "5d26336c37b3a9747d546430",
		},
		{
			iso_639_1: "en",
			iso_3166_1: "US",
			name: 'Lion King - "Can You Feel The Love Tonight?" Official Teaser Trailer',
			key: "SPuZoFTxHuw",
			site: "YouTube",
			size: 1080,
			type: "Teaser",
			official: false,
			published_at: "2019-06-24T02:38:45.000Z",
			id: "5d26332637b3a9747d5463b4",
		},
		{
			iso_639_1: "en",
			iso_3166_1: "US",
			name: "The Lion King Official Teaser (2019) Beyoncé as Nala",
			key: "hV0WtrFc3jc",
			site: "YouTube",
			size: 1080,
			type: "Featurette",
			official: false,
			published_at: "2019-06-03T22:30:02.000Z",
			id: "5d263354a698cf2b76a6acd4",
		},
		{
			iso_639_1: "en",
			iso_3166_1: "US",
			name: 'The Lion King Sneak Peek | "Come Home"',
			key: "hoGhxfndjpM",
			site: "YouTube",
			size: 1080,
			type: "Featurette",
			official: true,
			published_at: "2019-06-03T20:00:05.000Z",
			id: "5cfe4318c3a3680e921e7e17",
		},
		{
			iso_639_1: "en",
			iso_3166_1: "US",
			name: "The Lion King Official Trailer",
			key: "7TavVZMewpY",
			site: "YouTube",
			size: 1080,
			type: "Trailer",
			official: true,
			published_at: "2019-04-10T12:00:00.000Z",
			id: "5cade34d0e0a26310d5a7bc5",
		},
		{
			iso_639_1: "en",
			iso_3166_1: "US",
			name: "The Lion King | Long Live the King",
			key: "aQN75AKDwks",
			site: "YouTube",
			size: 1080,
			type: "Teaser",
			published_at: "2019-02-25T02:50:14.000Z",
			official: true,
			id: "5c7364950e0a262c09800374",
		},
		{
			iso_639_1: "en",
			iso_3166_1: "US",
			name: "The Lion King Official Teaser Trailer",
			key: "4CbLXeGSDxg",
			published_at: "2018-11-22T22:32:21.000Z",
			site: "YouTube",
			size: 1080,
			type: "Teaser",
			official: true,
			id: "5bf75c2f0e0a26266f0e1e04",
		},
	],
};
